<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../Shared.props" Condition="Exists('../Shared.props')" />
  <ItemGroup>
    <Compile Include="..\..\Plugins\UnrealCSharp\Script\UE\**" Exclude="..\..\Plugins\UnrealCSharp\Script\UE\**\*.DS_Store"></Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SourceGenerator\SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
  </ItemGroup>
</Project>