#include "Delegate/FUnrealCSharpModuleDelegates.h"

FUnrealCSharpModuleDelegates::FOnUnrealCSharpModuleActive FUnrealCSharpModuleDelegates::OnUnrealCSharpModuleActive;

FUnrealCSharpModuleDelegates::FOnUnrealCSharpModuleInActive FUnrealCSharpModuleDelegates::OnUnrealCSharpModuleInActive;

FUnrealCSharpModuleDelegates::FOnCSharpEnvironmentInitialize
FUnrealCSharpModuleDelegates::OnCSharpEnvironmentInitialize;
