using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace SourceGenerator
{
    [Generator]
    public class GameplayTagSourceGenerator : ISourceGenerator
    {
        private static readonly Regex TagRegex = new Regex(
            @"^\+GameplayTagList=\(Tag=""(?<tag>[^""]+)""(?:,DevComment=""(?<comment>[^""]*)"")?",
            RegexOptions.Compiled);

        public void Initialize(GeneratorInitializationContext Context)
        {
        }

        public void Execute(GeneratorExecutionContext Context)
        {
            var root = new TagNode();

            foreach (var additionalFile in Context.AdditionalFiles)
            {
                if (!Path.GetExtension(additionalFile.Path).Equals(".ini", StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                var text = additionalFile.GetText(Context.CancellationToken)?.ToString();

                if (string.IsNullOrEmpty(text))
                {
                    continue;
                }

                foreach (var rawLine in text.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries))
                {
                    var match = TagRegex.Match(rawLine.Trim());

                    if (!match.Success)
                    {
                        continue;
                    }

                    Insert(root, match.Groups["tag"].Value, match.Groups["comment"].Value);
                }
            }

            if (root.Children.Count == 0)
            {
                return;
            }

            var sb = new StringBuilder();

            var projectName = MakeUniqueIdentifier(
                string.IsNullOrEmpty(Context.Compilation.AssemblyName) ? "Game" : Context.Compilation.AssemblyName,
                new HashSet<string>(StringComparer.Ordinal));

            sb.AppendLine("// <auto-generated/> Generated from GameplayTags ini files");
            sb.AppendLine("using Script.GameplayTags;");
            sb.AppendLine();
            sb.AppendLine($"namespace Script.{projectName}");
            sb.AppendLine("{");
            sb.AppendLine("\tpublic static partial class GameplayTags");
            sb.AppendLine("\t{");

            EmitChildren(sb, root, 2);

            sb.AppendLine("\t}");
            sb.AppendLine("}");

            Context.AddSource($"Script.{projectName}.GameplayTags.gen.cs", sb.ToString());
        }

        private static void Insert(TagNode Root, string FullTag, string Comment)
        {
            var current = Root;

            foreach (var segment in FullTag.Split('.'))
            {
                if (!current.Children.TryGetValue(segment, out var child))
                {
                    child = new TagNode();
                    current.Children.Add(segment, child);
                }

                current = child;
            }

            current.FullTag = FullTag;
            current.Comment = Comment;
        }

        private static void EmitChildren(StringBuilder Sb, TagNode Node, int Indent)
        {
            var usedNames = new HashSet<string>(StringComparer.Ordinal);

            // "Value" is reserved for the tag registered on this class itself
            if (Node.FullTag != null)
            {
                usedNames.Add("Value");
            }

            foreach (var pair in Node.Children)
            {
                var name = MakeUniqueIdentifier(pair.Key, usedNames);
                var child = pair.Value;
                var pad = new string('\t', Indent);

                if (child.Children.Count == 0)
                {
                    EmitComment(Sb, pad, child.Comment);
                    Sb.AppendLine(
                        $"{pad}public static readonly FGameplayTag {name} = new FGameplayTag {{ TagName = \"{child.FullTag}\" }};");
                }
                else
                {
                    Sb.AppendLine($"{pad}public static class {name}");
                    Sb.AppendLine($"{pad}{{");

                    if (child.FullTag != null)
                    {
                        EmitComment(Sb, pad + "\t", child.Comment);
                        Sb.AppendLine(
                            $"{pad}\tpublic static readonly FGameplayTag Value = new FGameplayTag {{ TagName = \"{child.FullTag}\" }};");
                    }

                    EmitChildren(Sb, child, Indent + 1);

                    Sb.AppendLine($"{pad}}}");
                }
            }
        }

        private static void EmitComment(StringBuilder Sb, string Pad, string Comment)
        {
            if (!string.IsNullOrWhiteSpace(Comment))
            {
                Sb.AppendLine($"{Pad}/// <summary>{Comment.Replace("<", "&lt;").Replace(">", "&gt;")}</summary>");
            }
        }

        private static string MakeUniqueIdentifier(string Segment, HashSet<string> UsedNames)
        {
            var chars = Segment.Select(C => char.IsLetterOrDigit(C) || C == '_' ? C : '_').ToArray();

            var name = chars.Length == 0 ? "_" : new string(chars);

            if (char.IsDigit(name[0]))
            {
                name = "_" + name;
            }

            if (SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None ||
                SyntaxFacts.GetContextualKeywordKind(name) != SyntaxKind.None)
            {
                name = "@" + name;
            }

            var unique = name;
            var suffix = 2;

            while (!UsedNames.Add(unique))
            {
                unique = name + "_" + suffix++;
            }

            return unique;
        }

        private sealed class TagNode
        {
            public string FullTag;

            public string Comment;

            public readonly SortedDictionary<string, TagNode> Children =
                new SortedDictionary<string, TagNode>(StringComparer.Ordinal);
        }
    }
}