#include "Delegate/FUnrealCSharpCoreModuleDelegates.h"

FUnrealCSharpCoreModuleDelegates::FOnBeginGenerator FUnrealCSharpCoreModuleDelegates::OnBeginGenerator;

FUnrealCSharpCoreModuleDelegates::FOnEndGenerator FUnrealCSharpCoreModuleDelegates::OnEndGenerator;
