#include "Delegate/FUnrealCSharpCoreModuleDelegates.h"

FUnrealCSharpCoreModuleDelegates::FOnUnrealCSharpCoreModuleActive
FUnrealCSharpCoreModuleDelegates::OnUnrealCSharpCoreModuleActive;

FUnrealCSharpCoreModuleDelegates::FOnUnrealCSharpCoreModuleInActive
FUnrealCSharpCoreModuleDelegates::OnUnrealCSharpCoreModuleInActive;

FUnrealCSharpCoreModuleDelegates::FOnBeginGenerator FUnrealCSharpCoreModuleDelegates::OnBeginGenerator;

FUnrealCSharpCoreModuleDelegates::FOnEndGenerator FUnrealCSharpCoreModuleDelegates::OnEndGenerator;

FUnrealCSharpCoreModuleDelegates::FOnDynamicClassUpdated FUnrealCSharpCoreModuleDelegates::OnDynamicClassUpdated;
