#pragma once

#include "Macro.h"

#define IN_BUFFER InBuffer

#define IN_BUFFER_TEXT TEXT_STR(IN_BUFFER)

#define IN_BUFFER_SIGNATURE uint8* IN_BUFFER

#define OUT_BUFFER OutBuffer

#define OUT_BUFFER_TEXT TEXT_STR(OUT_BUFFER)

#define OUT_BUFFER_SIGNATURE uint8* OUT_BUFFER

#define RETURN_BUFFER ReturnBuffer

#define RETURN_BUFFER_TEXT TEXT_STR(RETURN_BUFFER)

#define RETURN_BUFFER_SIGNATURE uint8* RETURN_BUFFER

#define IN_KEY_BUFFER InKeyBuffer

#define IN_KEY_BUFFER_SIGNATURE uint8* IN_KEY_BUFFER

#define IN_VALUE_BUFFER InValueBuffer

#define IN_VALUE_BUFFER_SIGNATURE uint8* IN_VALUE_BUFFER
