#include "Reflection/FReflectionRegistry.h"
#include "CoreMacro/GenericAttributeMacro.h"
#include "CoreMacro/ClassAttributeMacro.h"
#include "CoreMacro/PropertyAttributeMacro.h"
#include "CoreMacro/FunctionAttributeMacro.h"
#include "CoreMacro/MetaDataAttributeMacro.h"

FReflectionRegistry& FReflectionRegistry::Get()
{
	static FReflectionRegistry ReflectionRegistry;
	
	return ReflectionRegistry;
}

FReflectionRegistry::FReflectionRegistry()
{
}

void FReflectionRegistry::Initialize()
{
	Byte_Class = FMonoDomain::Get_Byte_Class();
	
	Object_Class = FMonoDomain::Get_Object_Class();
	
	UInt16_Class = FMonoDomain::Get_UInt16_Class();
	
	UInt32_Class = FMonoDomain::Get_UInt32_Class();
	
	UInt64_Class = FMonoDomain::Get_UInt64_Class();
	
	SByte_Class = FMonoDomain::Get_SByte_Class();
	
	Int16_Class = FMonoDomain::Get_Int16_Class();
	
	Int32_Class = FMonoDomain::Get_Int32_Class();
	
	Int64_Class = FMonoDomain::Get_Int64_Class();
	
	Boolean_Class = FMonoDomain::Get_Boolean_Class();
	
	Single_Class = FMonoDomain::Get_Single_Class();
	
	Enum_Class = FMonoDomain::Get_Enum_Class();
	
	Double_Class = FMonoDomain::Get_Double_Class();
	
	Utils_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_CORE_UOBJECT), CLASS_UTILS);
	
	UClass_Class = GetClassReflection(UClass::StaticClass())->GetClass();
	
	TSubclassOf_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_CORE_UOBJECT), GENERIC_T_SUB_CLASS_OF)->GetClass();
	
	UObject_Class = GetClassReflection(UObject::StaticClass())->GetClass();
	
	Name_Class = GetClassReflection<FName>()->GetClass();
	
	TScriptInterface_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_CORE_UOBJECT), GENERIC_T_SCRIPT_INTERFACE)->GetClass();
	
	String_Class = GetClassReflection<FString>()->GetClass();
	
#if UE_F_UTF8_STR_PROPERTY
	Utf8String_Class = GetClassReflection<FUtf8String>()->GetClass();
#endif
	
#if UE_F_ANSI_STR_PROPERTY
	AnsiString_Class = GetClassReflection<FAnsiString>()->GetClass();
#endif
	
	Text_Class = GetClassReflection<FText>()->GetClass();
	
	TWeakObjectPtr_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_CORE_UOBJECT), GENERIC_T_WEAK_OBJECT_PTR)->GetClass();

	TLazyObjectPtr_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_CORE_UOBJECT), GENERIC_T_LAZY_OBJECT_PTR)->GetClass();
	
	TSoftClassPtr_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_CORE_UOBJECT), GENERIC_T_SOFT_CLASS_PTR)->GetClass();

	TSoftObjectPtr_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_CORE_UOBJECT), GENERIC_T_SOFT_OBJECT_PTR)->GetClass();

	TMap_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_CORE_UOBJECT), GENERIC_T_MAP)->GetClass();
	
	TSet_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_CORE_UOBJECT), GENERIC_T_SET)->GetClass();
	
	TArray_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_CORE_UOBJECT), GENERIC_T_ARRAY)->GetClass();
	
#if UE_F_OPTIONAL_PROPERTY
	TOptional_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_CORE_UOBJECT), GENERIC_T_OPTIONAL)->GetClass();
#endif
	
	UClassAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_U_CLASS_ATTRIBUTE)->GetClass();
	
	UStructAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_U_STRUCT_ATTRIBUTE)->GetClass();
	
	UEnumAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_U_ENUM_ATTRIBUTE)->GetClass();
	
	UPropertyAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_U_PROPERTY_ATTRIBUTE)->GetClass();

	UFunctionAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_U_FUNCTION_ATTRIBUTE)->GetClass();
	
	UInterfaceAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_U_INTERFACE_ATTRIBUTE)->GetClass();
	
	
	
	
	VisibleInstanceOnlyAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_VISIBLE_INSTANCE_ONLY_ATTRIBUTE)->GetClass();
	
	BlueprintCallableAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_CALLABLE_ATTRIBUTE)->GetClass();

	BlueprintAuthorityOnlyAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_AUTHORITY_ONLY_ATTRIBUTE)->GetClass();

	BlueprintGetterAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_GETTER_ATTRIBUTE)->GetClass();

	BlueprintSetterAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_SETTER_ATTRIBUTE)->GetClass();

	FieldNotifyAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_FIELD_NOTIFY_ATTRIBUTE)->GetClass();

	TransientAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_TRANSIENT_ATTRIBUTE)->GetClass();

	ConfigAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CONFIG_ATTRIBUTE)->GetClass();

	BlueprintTypeAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_TYPE_ATTRIBUTE)->GetClass();

	NotBlueprintTypeAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NOT_BLUEPRINT_TYPE_ATTRIBUTE)->GetClass();
	
	BlueprintableAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINTABLE_ATTRIBUTE)->GetClass();
	
	NotBlueprintableAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NOT_BLUEPRINTABLE_ATTRIBUTE)->GetClass();
	
	NoExportAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NO_EXPORT_ATTRIBUTE)->GetClass();
	
	AbstractAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ABSTRACT_ATTRIBUTE)->GetClass();
	
	ExperimentalAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EXPERIMENTAL_ATTRIBUTE)->GetClass();
	
	EditorConfigAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EDITOR_CONFIG_ATTRIBUTE)->GetClass();
	
	
	
	ClassGroupAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CLASS_GROUP_ATTRIBUTE)->GetClass();
	
	WithinAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_WITHIN_ATTRIBUTE)->GetClass();
	
	MinimalAPIAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_MINIMAL_API_ATTRIBUTE)->GetClass();
	
	CustomConstructorAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CUSTOM_CONSTRUCTOR_ATTRIBUTE)->GetClass();
	
	IntrinsicAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_INTRINSIC_ATTRIBUTE)->GetClass();
	
	NotPlaceableAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NOT_PLACEABLE_ATTRIBUTE)->GetClass();
	
	DefaultToInstancedAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DEFAULT_TO_INSTANCED_ATTRIBUTE)->GetClass();
	
	ConstAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CONST_ATTRIBUTE)->GetClass();
	
	DeprecatedAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DEPRECATED_ATTRIBUTE)->GetClass();
	
	PerObjectConfigAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_PER_OBJECT_CONFIG_ATTRIBUTE)->GetClass();
	
	ConfigDoNotCheckDefaultsAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CONFIG_DO_NOT_CHECK_DEFAULTS_ATTRIBUTE)->GetClass();
	
	DefaultConfigAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DEFAULT_CONFIG_ATTRIBUTE)->GetClass();
	
	EditInlineNewAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EDIT_INLINE_NEW_ATTRIBUTE)->GetClass();
	
	NotEditInlineNewAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NOT_EDIT_INLINE_NEW_ATTRIBUTE)->GetClass();
	
	HideDropdownAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_HIDE_DROP_DOWN_ATTRIBUTE)->GetClass();
	
	ShowCategoriesAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SHOW_CATEGORIES_ATTRIBUTE)->GetClass();
	
	ComponentWrapperClassAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_COMPONENT_WRAPPER_CLASS_ATTRIBUTE)->GetClass();
	
	HideFunctionsAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_HIDE_FUNCTIONS_ATTRIBUTE)->GetClass();
	
	AutoExpandCategoriesAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_AUTO_EXPAND_CATEGORIES_ATTRIBUTE)->GetClass();
	
	AutoCollapseCategoriesAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_AUTO_COLLAPSE_CATEGORIES_ATTRIBUTE)->GetClass();
	
	CollapseCategoriesAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_COLLAPSE_CATEGORIES_ATTRIBUTE)->GetClass();
	
	DontCollapseCategoriesAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DONT_COLLAPSE_CATEGORIES_ATTRIBUTE)->GetClass();
	
	PrioritizeCategoriesAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_PRIORITIZE_CATEGORIES_ATTRIBUTE)->GetClass();
	
	AdvancedClassDisplayAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ADVANCED_CLASS_DISPLAY_ATTRIBUTE)->GetClass();
	
	EarlyAccessPreviewAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EARLY_ACCESS_PREVIEW_ATTRIBUTE)->GetClass();

	SparseClassDataTypeAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SPARSE_CLASS_DATA_TYPE_ATTRIBUTE)->GetClass();

	GlobalConfigAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_GLOBAL_CONFIG_ATTRIBUTE)->GetClass();

	LocalizedAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_LOCALIZED_ATTRIBUTE)->GetClass();

	DuplicateTransientAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DUPLICATE_TRANSIENT_ATTRIBUTE)->GetClass();

	NonPIETransientAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NON_PIE_TRANSIENT_ATTRIBUTE)->GetClass();

	NonPIEDuplicateTransientAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NON_PIE_DUPLICATE_TRANSIENT_ATTRIBUTE)->GetClass();

	ExportAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EXPORT_ATTRIBUTE)->GetClass();

	NoClearAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NO_CLEAR_ATTRIBUTE)->GetClass();

	EditFixedSizeAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EDIT_FIXED_SIZE_ATTRIBUTE)->GetClass();

	ReplicatedAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_REPLICATED_ATTRIBUTE)->GetClass();

	ReplicatedUsingAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_REPLICATED_USING_ATTRIBUTE)->GetClass();

	NotReplicatedAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NOT_REPLICATED_ATTRIBUTE)->GetClass();

	InterpAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_INTERP_ATTRIBUTE)->GetClass();

	NonTransactionalAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NON_TRANSACTIONAL_ATTRIBUTE)->GetClass();

	InstancedAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_INSTANCED_ATTRIBUTE)->GetClass();

	BlueprintAssignableAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_ASSIGNABLE_ATTRIBUTE)->GetClass();
	
	SimpleDisplayAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SIMPLE_DISPLAY_ATTRIBUTE)->GetClass();
	
	AdvancedDisplayAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ADVANCED_DISPLAY_ATTRIBUTE)->GetClass();
	
	EditAnywhereAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EDIT_ANYWHERE_ATTRIBUTE)->GetClass();
	
	EditInstanceOnlyAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EDIT_INSTANCE_ONLY_ATTRIBUTE)->GetClass();
	
	EditDefaultsOnlyAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EDIT_DEFAULTS_ONLY_ATTRIBUTE)->GetClass();
	
	VisibleAnywhereAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_VISIBLE_ANYWHERE_ATTRIBUTE)->GetClass();
	
	VisibleDefaultsOnlyAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_VISIBLE_DEFAULTS_ONLY_ATTRIBUTE)->GetClass();
	
	BlueprintReadOnlyAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_READ_ONLY_ATTRIBUTE)->GetClass();
	
	BlueprintReadWriteAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_READ_WRITE_ATTRIBUTE)->GetClass();
	
	AssetRegistrySearchableAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ASSET_REGISTRY_SEARCHABLE_ATTRIBUTE)->GetClass();
	
	SaveGameAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SAVE_GAME_ATTRIBUTE)->GetClass();
	
	TextExportTransientAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_TEXT_EXPORT_TRANSIENT_ATTRIBUTE)->GetClass();
	
	SkipSerializationAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SKIP_SERIALIZATION_ATTRIBUTE)->GetClass();
	
	DefaultSubObjectAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DEFAULT_SUB_OBJECT_ATTRIBUTE)->GetClass();
	
	RootComponentAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ROOT_COMPONENT_ATTRIBUTE)->GetClass();
	
	AttachmentParentAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ATTACHMENT_PARENT_ATTRIBUTE)->GetClass();
	
	AttachmentSocketNameAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ATTACHMENT_SOCKET_NAME_ATTRIBUTE)->GetClass();
	
	DefaultValueAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DEFAULT_VALUE_ATTRIBUTE)->GetClass();
	
	
	BlueprintImplementableEventAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_IMPLEMENTABLE_EVENT_ATTRIBUTE)->GetClass();

	SealedEventAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SEALED_EVENT_ATTRIBUTE)->GetClass();

	ExecAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EXEC_ATTRIBUTE)->GetClass();

	ServerAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SERVER_ATTRIBUTE)->GetClass();

	ClientAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CLIENT_ATTRIBUTE)->GetClass();

	NetMulticastAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NET_MULTICAST_ATTRIBUTE)->GetClass();

	ReliableAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_RELIABLE_ATTRIBUTE)->GetClass();

	UnreliableAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_UNRELIABLE_ATTRIBUTE)->GetClass();

	BlueprintPureAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_PURE_ATTRIBUTE)->GetClass();

	BlueprintCosmeticAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_COSMETIC_ATTRIBUTE)->GetClass();

	CustomThunkAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CUSTOM_THUNK_ATTRIBUTE)->GetClass();

	WithValidationAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_WITH_VALIDATION_ATTRIBUTE)->GetClass();

	ServiceRequestAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SERVICE_REQUEST_ATTRIBUTE)->GetClass();

	ServiceResponseAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SERVICE_RESPONSE_ATTRIBUTE)->GetClass();
	
	// MetaDataAttributeMacro.h - 按顺序添加
#if WITH_EDITOR
	HideCategoriesAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_HIDE_CATEGORIES_ATTRIBUTE);
	
	ConversionRootAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CONVERSION_ROOT_ATTRIBUTE);
	
	CannotImplementInterfaceInBlueprintAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CANNOT_IMPLEMENT_INTERFACE_IN_BLUEPRINT_ATTRIBUTE);
	
	ToolTipAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_TOOLTIP_ATTRIBUTE);
	
	ShortTooltipAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SHORT_TOOLTIP_ATTRIBUTE);
	
	DocumentationPolicyAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DOCUMENTATION_POLICY_ATTRIBUTE);
	
	BlueprintSpawnableComponentAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_SPAWNABLE_COMPONENT_ATTRIBUTE);
	
	ChildCanTickAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CHILD_CAN_TICK_ATTRIBUTE);
	
	ChildCannotTickAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CHILD_CANNOT_TICK_ATTRIBUTE);
	
	DebugTreeLeafAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DEBUG_TREE_LEAF_ATTRIBUTE);
	
	IgnoreCategoryKeywordsInSubclassesAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_IGNORE_CATEGORY_KEYWORDS_IN_SUBCLASSES_ATTRIBUTE);
	
	DeprecatedNodeAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DEPRECATED_NODE_ATTRIBUTE);
	
	DeprecationMessageAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DEPRECATION_MESSAGE_ATTRIBUTE);
	
	DisplayNameAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DISPLAY_NAME_ATTRIBUTE);
	
	ScriptNameAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SCRIPT_NAME_ATTRIBUTE);
	
	IsBlueprintBaseAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_IS_BLUEPRINT_BASE_ATTRIBUTE);
	
	KismetHideOverridesAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_KISMET_HIDE_OVERRIDES_ATTRIBUTE);
	
	LoadBehaviorAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_LOAD_BEHAVIOR_ATTRIBUTE);
	
	ProhibitedInterfacesAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_PROHIBITED_INTERFACES_ATTRIBUTE);
	
	RestrictedToClassesAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_RESTRICTED_TO_CLASSES_ATTRIBUTE);
	
	ShowWorldContextPinAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SHOW_WORLD_CONTEXT_PIN_ATTRIBUTE);
	
	DontUseGenericSpawnObjectAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DONT_USE_GENERIC_SPAWN_OBJECT_ATTRIBUTE);
	
	ExposedAsyncProxyAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EXPOSED_ASYNC_PROXY_ATTRIBUTE);
	
	BlueprintThreadSafeAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_THREAD_SAFE_ATTRIBUTE);
	
	UsesHierarchyAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_USES_HIERARCHY_ATTRIBUTE);
	
	HasNativeBreakAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_HAS_NATIVE_BREAK_ATTRIBUTE);
	
	HasNativeMakeAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_HAS_NATIVE_MAKE_ATTRIBUTE);
	
	HiddenByDefaultAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_HIDDEN_BY_DEFAULT_ATTRIBUTE);
	
	DisableSplitPinAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DISABLE_SPLIT_PIN_ATTRIBUTE);
	
	AllowAbstractAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ALLOW_ABSTRACT_ATTRIBUTE);
	
	AllowAnyActorAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ALLOW_ANY_ACTOR_ATTRIBUTE);
	
	AllowedClassesAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ALLOWED_CLASSES_ATTRIBUTE);
	
	AllowPreserveRatioAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ALLOW_PRESERVE_RATIO_ATTRIBUTE);
	
	AllowPrivateAccessAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ALLOW_PRIVATE_ACCESS_ATTRIBUTE);
	
	ArrayClampAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ARRAY_CLAMP_ATTRIBUTE);
	
	AssetBundlesAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ASSET_BUNDLES_ATTRIBUTE);
	
	BlueprintBaseOnlyAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_BASE_ONLY_ATTRIBUTE);
	
	BlueprintCompilerGeneratedDefaultsAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_COMPILER_GENERATED_DEFAULTS_ATTRIBUTE);
	
	ClampMinAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CLAMP_MIN_ATTRIBUTE);
	
	ClampMaxAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CLAMP_MAX_ATTRIBUTE);
	
	ConfigHierarchyEditableAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CONFIG_HIERARCHY_EDITABLE_ATTRIBUTE);
	
	ContentDirAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CONTENT_DIR_ATTRIBUTE);
	
	DeltaAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DELTA_ATTRIBUTE);
	
	DeprecatedPropertyAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DEPRECATED_PROPERTY_ATTRIBUTE);
	
	DisallowedAssetDataTagsAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DISALLOWED_ASSET_DATA_TAGS_ATTRIBUTE);
	
	DisallowedClassesAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DISALLOWED_CLASSES_ATTRIBUTE);
	
	DisplayAfterAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DISPLAY_AFTER_ATTRIBUTE);
	
	DisplayPriorityAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DISPLAY_PRIORITY_ATTRIBUTE);
	
	DisplayThumbnailAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DISPLAY_THUMBNAIL_ATTRIBUTE);
	
	EditConditionAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EDIT_CONDITION_ATTRIBUTE);
	
	EditConditionHidesAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EDIT_CONDITION_HIDES_ATTRIBUTE);
	
	EditFixedOrderAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EDIT_FIXED_ORDER_ATTRIBUTE);
	
	CategoryAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CATEGORY_ATTRIBUTE);
	
	ExactClassAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EXACT_CLASS_ATTRIBUTE);
	
	ExposeFunctionCategoriesAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EXPOSE_FUNCTION_CATEGORIES_ATTRIBUTE);
	
	ExposeOnSpawnAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EXPOSE_ON_SPAWN_ATTRIBUTE);
	
	FilePathFilterAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_FILE_PATH_FILTER_ATTRIBUTE);
	
	RelativeToGameDirAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_RELATIVE_TO_GAME_DIR_ATTRIBUTE);
	
	FixedIncrementAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_FIXED_INCREMENT_ATTRIBUTE);
	
	ForceShowEngineContentAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_FORCE_SHOW_ENGINE_CONTENT_ATTRIBUTE);
	
	ForceShowPluginContentAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_FORCE_SHOW_PLUGIN_CONTENT_ATTRIBUTE);
	
	HideAlphaChannelAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_HIDE_ALPHA_CHANNEL_ATTRIBUTE);
	
	HideInDetailPanelAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_HIDE_IN_DETAIL_PANEL_ATTRIBUTE);
	
	HideViewOptionsAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_HIDE_VIEW_OPTIONS_ATTRIBUTE);
	
	IgnoreForMemberInitializationTestAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_IGNORE_FOR_MEMBER_INITIALIZATION_TEST_ATTRIBUTE);
	
	InlineEditConditionToggleAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_INLINE_EDIT_CONDITION_TOGGLE_ATTRIBUTE);
	
	LinearDeltaSensitivityAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_LINEAR_DELTA_SENSITIVITY_ATTRIBUTE);
	
	LongPackageNameAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_LONG_PACKAGE_NAME_ATTRIBUTE);
	
	MakeEditWidgetAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_MAKE_EDIT_WIDGET_ATTRIBUTE);
	
	MakeStructureDefaultValueAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_MAKE_STRUCTURE_DEFAULT_VALUE_ATTRIBUTE);
	
	MetaClassAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_META_CLASS_ATTRIBUTE);
	
	MustImplementAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_MUST_IMPLEMENT_ATTRIBUTE);
	
	MultipleAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_MULTIPLE_ATTRIBUTE);
	
	MaxLengthAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_MAX_LENGTH_ATTRIBUTE);
	
	MultiLineAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_MULTILINE_ATTRIBUTE);
	
	PasswordFieldAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_PASSWORD_FIELD_ATTRIBUTE);
	
	NoElementDuplicateAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NO_ELEMENT_DUPLICATE_ATTRIBUTE);
	
	NoResetToDefaultAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NO_RESET_TO_DEFAULT_ATTRIBUTE);
	
	EditInlineAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EDIT_INLINE_ATTRIBUTE);
	
	NoEditInlineAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NO_EDIT_INLINE_ATTRIBUTE);
	
	NoSpinboxAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NO_SPIN_BOX_ATTRIBUTE);
	
	OnlyPlaceableAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ONLY_PLACEABLE_ATTRIBUTE);
	
	RelativePathAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_RELATIVE_PATH_ATTRIBUTE);
	
	RelativeToGameContentDirAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_RELATIVE_TO_GAME_CONTENT_DIR_ATTRIBUTE);
	
	RequiredAssetDataTagsAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_REQUIRED_ASSET_DATA_TAGS_ATTRIBUTE);
	
	ScriptNoExportAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SCRIPT_NO_EXPORT_ATTRIBUTE);
	
	ShowOnlyInnerPropertiesAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SHOW_ONLY_INNER_PROPERTIES_ATTRIBUTE);
	
	ShowTreeViewAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SHOW_TREE_VIEW_ATTRIBUTE);
	
	SliderExponentAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SLIDER_EXPONENT_ATTRIBUTE);
	
	TitlePropertyAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_TITLE_PROPERTY_ATTRIBUTE);
	
	UIMinAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_UI_MIN_ATTRIBUTE);
	
	UIMaxAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_UI_MAX_ATTRIBUTE);
	
	UnitsAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_UNITS_ATTRIBUTE);
	
	ForceUnitsAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_FORCE_UNITS_ATTRIBUTE);
	
	UntrackedAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_UNTRACKED_ATTRIBUTE);
	
	DevelopmentOnlyAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DEVELOPMENT_ONLY_ATTRIBUTE);
	
	NeedsLatentFixupAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NEEDS_LATENT_FIXUP_ATTRIBUTE);
	
	LatentCallbackTargetAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_LATENT_CALLBACK_TARGET_ATTRIBUTE);
	
	GetOptionsAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_GET_OPTIONS_ATTRIBUTE);
	
	PinHiddenByDefaultAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_PIN_HIDDEN_BY_DEFAULT_ATTRIBUTE);
	
	ValidEnumValuesAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_VALID_ENUM_VALUES_ATTRIBUTE);
	
	InvalidEnumValuesAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_INVALID_ENUM_VALUES_ATTRIBUTE);
	
	OverridingInputPropertyAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_OVERRIDING_INPUT_PROPERTY_ATTRIBUTE);
	
	RequiredInputAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_REQUIRED_INPUT_ATTRIBUTE);
	
	NeverAsPinAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NEVER_AS_PIN_ATTRIBUTE);
	
	PinShownByDefaultAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_PIN_SHOWN_BY_DEFAULT_ATTRIBUTE);
	
	AlwaysAsPinAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ALWAYS_AS_PIN_ATTRIBUTE);
	
	CustomizePropertyAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CUSTOMIZE_PROPERTY_ATTRIBUTE);
	
	CallInEditorAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CALL_IN_EDITOR_ATTRIBUTE);
	
	VariadicAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_VARIADIC_ATTRIBUTE);
	
	ReturnDisplayNameAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_RETURN_DISPLAY_NAME_ATTRIBUTE);
	
	InternalUseParamAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_INTERNAL_USE_PARAM_ATTRIBUTE);
	
	ForceAsFunctionAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_FORCE_AS_FUNCTION_ATTRIBUTE);
	
	IgnoreTypePromotionAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_IGNORE_TYPE_PROMOTION_ATTRIBUTE);
	
	ArrayParmAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ARRAY_PARM_ATTRIBUTE);
	
	ArrayTypeDependentParamsAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ARRAY_TYPE_DEPENDENT_PARAMS_ATTRIBUTE);
	
	AutoCreateRefTermAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_AUTO_CREATE_REF_TERM_ATTRIBUTE);
	
	HideAssetPickerAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_HIDE_ASSET_PICKER_ATTRIBUTE);
	
	BlueprintInternalUseOnlyAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_INTERNAL_USE_ONLY_ATTRIBUTE);
	
	BlueprintProtectedAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_PROTECTED_ATTRIBUTE);
	
	CallableWithoutWorldContextAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CALLABLE_WITHOUT_WORLD_CONTEXT_ATTRIBUTE);
	
	CommutativeAssociativeBinaryOperatorAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_COMMUTATIVE_ASSOCIATIVE_BINARY_OPERATOR_ATTRIBUTE);
	
	CompactNodeTitleAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_COMPACT_NODE_TITLE_ATTRIBUTE);
	
	CustomStructureParamAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CUSTOM_STRUCTURE_PARAM_ATTRIBUTE);
	
	DefaultToSelfAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DEFAULT_TO_SELF_ATTRIBUTE);
	
	DeprecatedFunctionAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DEPRECATED_FUNCTION_ATTRIBUTE);
	
	ExpandEnumAsExecsAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EXPAND_ENUM_AS_EXECS_ATTRIBUTE);
	
	ExpandBoolAsExecsAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EXPAND_BOOL_AS_EXECS_ATTRIBUTE);
	
	ScriptMethodAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SCRIPT_METHOD_ATTRIBUTE);
	
	ScriptMethodSelfReturnAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SCRIPT_METHOD_SELF_RETURN_ATTRIBUTE);
	
	ScriptOperatorAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SCRIPT_OPERATOR_ATTRIBUTE);
	
	ScriptConstantAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SCRIPT_CONSTANT_ATTRIBUTE);
	
	ScriptConstantHostAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SCRIPT_CONSTANT_HOST_ATTRIBUTE);
	
	HidePinAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_HIDE_PIN_ATTRIBUTE);
	
	HideSpawnParmsAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_HIDE_SPAWN_PARMS_ATTRIBUTE);
	
	KeywordsAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_KEYWORDS_ATTRIBUTE);
	
	LatentAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_LATENT_ATTRIBUTE);
	
	LatentInfoAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_LATENT_INFO_ATTRIBUTE);
	
	MaterialParameterCollectionFunctionAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_MATERIAL_PARAMETER_COLLECTION_FUNCTION_ATTRIBUTE);
	
	NativeBreakFuncAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NATIVE_BREAK_FUNC_ATTRIBUTE);
	
	NativeMakeFuncAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NATIVE_MAKE_FUNC_ATTRIBUTE);
	
	UnsafeDuringActorConstructionAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_UNSAFE_DURING_ACTOR_CONSTRUCTION_ATTRIBUTE);
	
	WorldContextAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_WORLD_CONTEXT_ATTRIBUTE);
	
	BlueprintAutoCastAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_AUTO_CAST_ATTRIBUTE);
	
	NotBlueprintThreadSafeAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NOT_BLUEPRINT_THREAD_SAFE_ATTRIBUTE);
	
	DeterminesOutputTypeAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DETERMINES_OUTPUT_TYPE_ATTRIBUTE);
	
	DynamicOutputParamAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DYNAMIC_OUTPUT_PARAM_ATTRIBUTE);
	
	DataTablePinAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DATA_TABLE_PIN_ATTRIBUTE);
	
	SetParamAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SET_PARAM_ATTRIBUTE);
	
	MapParamAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_MAP_PARAM_ATTRIBUTE);
	
	MapKeyParamAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_MAP_KEY_PARAM_ATTRIBUTE);
	
	MapValueParamAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_MAP_VALUE_PARAM_ATTRIBUTE);
	
	BitmaskAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BIT_MASK_ATTRIBUTE);
	
	BitmaskEnumAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BIT_MASK_ENUM_ATTRIBUTE);
	
	BitflagsAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BITFLAGS_ATTRIBUTE);
	
	UseEnumValuesAsMaskValuesInEditorAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_USE_ENUM_VALUES_AS_MASK_VALUES_IN_EDITOR);
	
	ArrayParamAttribute_Class = GetClassReflection(COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ARRAY_PARAM_ATTRIBUTE);
#endif
}

void FReflectionRegistry::Deinitialize()
{
	ClassReflection.Empty();
	
	ClassReflection1.Empty();
	
	ClassReflection2.Empty();
}

FClassReflection* FReflectionRegistry::GetClassReflection(const TWeakObjectPtr<UField>& InStruct)
{
	if (const auto FoundClassReflection = ClassReflection.Find(InStruct))
	{
		return *FoundClassReflection;
	}
	
	if (const auto FoundMonoClass = FClassReflection::GetMonoClass(InStruct))
	{
		auto Class = new FClassReflection(InStruct, FoundMonoClass);
		
		ClassReflection.Add(InStruct, Class);
		
		ClassReflection1.Add(FoundMonoClass, Class);
		
		return Class;
	}
	
	return nullptr;
}

FClassReflection* FReflectionRegistry::GetClassReflection(MonoClass* InStruct)
{
	if (const auto FoundClassReflection = ClassReflection1.Find(InStruct))
	{
		return *FoundClassReflection;
	}
	
	return ClassReflection1.Add(InStruct, new FClassReflection(InStruct));
}

FClassReflection* FReflectionRegistry::GetClassReflection(const FString& InNameSpace, const FString& InMonoClassName)
{
	auto Pair = TPair<FString, FString>(InNameSpace, InMonoClassName);
	
	if (const auto FoundClassReflection = ClassReflection2.Find(Pair))
	{
		return *FoundClassReflection;
	}
	
	if (auto Class1 = FMonoDomain::Class_From_Name(InNameSpace, InMonoClassName))
	{
		auto Class = new FClassReflection(InMonoClassName, Class1);
		
		ClassReflection1.Add(Class1, Class);
		
		ClassReflection2.Add(Pair, Class);
		
		return Class;
	}
	
	return nullptr;
}

MonoClass* FReflectionRegistry::Get_Byte_Class() const
{
	return Byte_Class;
}

MonoClass* FReflectionRegistry::Get_Object_Class() const
{
	return Object_Class;
}

MonoClass* FReflectionRegistry::Get_UInt16_Class() const
{
	return UInt16_Class;
}

MonoClass* FReflectionRegistry::Get_UInt32_Class() const
{
	return UInt32_Class;
}

MonoClass* FReflectionRegistry::Get_UInt64_Class() const
{
	return UInt64_Class;
}

MonoClass* FReflectionRegistry::Get_SByte_Class() const
{
	return SByte_Class;
}

MonoClass* FReflectionRegistry::Get_Int16_Class() const
{
	return Int16_Class;
}

MonoClass* FReflectionRegistry::Get_Int32_Class() const
{
	return Int32_Class;
}

MonoClass* FReflectionRegistry::Get_Int64_Class() const
{
	return Int64_Class;
}

MonoClass* FReflectionRegistry::Get_Boolean_Class() const
{
	return Boolean_Class;
}

MonoClass* FReflectionRegistry::Get_Single_Class() const
{
	return Single_Class;
}

MonoClass* FReflectionRegistry::Get_Enum_Class() const
{
	return Enum_Class;
}

MonoClass* FReflectionRegistry::Get_Double_Class() const
{
	return Double_Class;
}

MonoClass* FReflectionRegistry::Get_UClass_Class() const
{
	return UClass_Class;
}

MonoClass* FReflectionRegistry::Get_UObject_Class() const
{
	return UObject_Class;
}

MonoClass* FReflectionRegistry::Get_TSubclassOf_Class() const
{
	return TSubclassOf_Class;
}

MonoClass* FReflectionRegistry::Get_Name_Class() const
{
	return Name_Class;
}

MonoClass* FReflectionRegistry::Get_TScriptInterface_Class()
{
	return TScriptInterface_Class;
}

MonoClass* FReflectionRegistry::Get_String_Class() const
{
	return String_Class;
}

#if UE_F_UTF8_STR_PROPERTY
MonoClass* FReflectionRegistry::Get_Utf8String_Class() const
{
	return Utf8String_Class;
}
#endif

#if UE_F_ANSI_STR_PROPERTY
MonoClass* FReflectionRegistry::Get_AnsiString_Class() const
{
	return AnsiString_Class;
}
#endif

MonoClass* FReflectionRegistry::Get_Text_Class() const
{
	return Text_Class;
}

MonoClass* FReflectionRegistry::Get_TWeakObjectPtr_Class() const
{
	return TWeakObjectPtr_Class;
}

MonoClass* FReflectionRegistry::Get_TLazyObjectPtr_Class() const
{
	return TLazyObjectPtr_Class;
}

MonoClass* FReflectionRegistry::Get_TSoftClassPtr_Class() const
{
	return TSoftClassPtr_Class;
}

MonoClass* FReflectionRegistry::Get_TSoftObjectPtr_Class() const
{
	return TSoftObjectPtr_Class;
}

MonoClass* FReflectionRegistry::Get_TMap_Class() const
{
	return TMap_Class;
}

MonoClass* FReflectionRegistry::Get_TSet_Class() const
{
	return TSet_Class;
}

MonoClass* FReflectionRegistry::GetTArray_Class() const
{
	return TArray_Class;
}

#if UE_F_OPTIONAL_PROPERTY
MonoClass* FReflectionRegistry::GetTOptional_Class() const
{
	return TOptional_Class;
}
#endif

MonoClass* FReflectionRegistry::GetUClassAttribute_Class() const
{
	return UClassAttribute_Class;
}

MonoClass* FReflectionRegistry::GetUStructAttribute_Class() const
{
	return UStructAttribute_Class;
}

MonoClass* FReflectionRegistry::GetUEnumAttribute_Class() const
{
	return UEnumAttribute_Class;
}

MonoClass* FReflectionRegistry::GetUInterfaceAttribute_Class() const
{
	return UInterfaceAttribute_Class;
}

MonoClass* FReflectionRegistry::GetUPropertyAttribute_Class() const
{
	return UPropertyAttribute_Class;
}

MonoClass* FReflectionRegistry::GetUFunctionAttribute_Class() const
{
	return UFunctionAttribute_Class;
}

MonoClass* FReflectionRegistry::GetVisibleInstanceOnlyAttribute_Class() const
{
	return VisibleInstanceOnlyAttribute_Class;
}

MonoClass* FReflectionRegistry::GetBlueprintCallableAttribute_Class() const
{
	return BlueprintCallableAttribute_Class;
}

MonoClass* FReflectionRegistry::GetBlueprintAuthorityOnlyAttribute_Class() const
{
	return BlueprintAuthorityOnlyAttribute_Class;
}

MonoClass* FReflectionRegistry::GetBlueprintGetterAttribute_Class() const
{
	return BlueprintGetterAttribute_Class;
}

MonoClass* FReflectionRegistry::GetBlueprintSetterAttribute_Class() const
{
	return BlueprintSetterAttribute_Class;
}

MonoClass* FReflectionRegistry::GetFieldNotifyAttribute_Class() const
{
	return FieldNotifyAttribute_Class;
}

MonoClass* FReflectionRegistry::GetTransientAttribute_Class() const
{
	return TransientAttribute_Class;
}

MonoClass* FReflectionRegistry::GetConfigAttribute_Class() const
{
	return ConfigAttribute_Class;
}

MonoClass* FReflectionRegistry::GetBlueprintTypeAttribute_Class() const
{
	return BlueprintTypeAttribute_Class;
}

MonoClass* FReflectionRegistry::GetNotBlueprintTypeAttribute_Class() const
{
	return NotBlueprintTypeAttribute_Class;
}

MonoClass* FReflectionRegistry::GetBlueprintableAttribute_Class() const
{
	return BlueprintableAttribute_Class;
}

MonoClass* FReflectionRegistry::GetNotBlueprintableAttribute_Class() const
{
	return NotBlueprintableAttribute_Class;
}

MonoClass* FReflectionRegistry::GetNoExportAttribute_Class() const
{
	return NoExportAttribute_Class;
}

MonoClass* FReflectionRegistry::GetAbstractAttribute_Class() const
{
	return AbstractAttribute_Class;
}

MonoClass* FReflectionRegistry::GetExperimentalAttribute_Class() const
{
	return ExperimentalAttribute_Class;
}

MonoClass* FReflectionRegistry::GetEditorConfigAttribute_Class() const
{
	return EditorConfigAttribute_Class;
}

MonoClass* FReflectionRegistry::GetClassGroupAttribute_Class() const
{
	return ClassGroupAttribute_Class;
}

MonoClass* FReflectionRegistry::GetWithinAttribute_Class() const
{
	return WithinAttribute_Class;
}

MonoClass* FReflectionRegistry::GetMinimalAPIAttribute_Class() const
{
	return MinimalAPIAttribute_Class;
}

MonoClass* FReflectionRegistry::GetCustomConstructorAttribute_Class() const
{
	return CustomConstructorAttribute_Class;
}

MonoClass* FReflectionRegistry::GetIntrinsicAttribute_Class() const
{
	return IntrinsicAttribute_Class;
}

MonoClass* FReflectionRegistry::GetNotPlaceableAttribute_Class() const
{
	return NotPlaceableAttribute_Class;
}

MonoClass* FReflectionRegistry::GetDefaultToInstancedAttribute_Class() const
{
	return DefaultToInstancedAttribute_Class;
}

MonoClass* FReflectionRegistry::GetConstAttribute_Class() const
{
	return ConstAttribute_Class;
}

MonoClass* FReflectionRegistry::GetDeprecatedAttribute_Class() const
{
	return DeprecatedAttribute_Class;
}

MonoClass* FReflectionRegistry::GetPerObjectConfigAttribute_Class() const
{
	return PerObjectConfigAttribute_Class;
}

MonoClass* FReflectionRegistry::GetConfigDoNotCheckDefaultsAttribute_Class() const
{
	return ConfigDoNotCheckDefaultsAttribute_Class;
}

MonoClass* FReflectionRegistry::GetDefaultConfigAttribute_Class() const
{
	return DefaultConfigAttribute_Class;
}

MonoClass* FReflectionRegistry::GetEditInlineNewAttribute_Class() const
{
	return EditInlineNewAttribute_Class;
}

MonoClass* FReflectionRegistry::GetNotEditInlineNewAttribute_Class() const
{
	return NotEditInlineNewAttribute_Class;
}

MonoClass* FReflectionRegistry::GetHideDropdownAttribute_Class() const
{
	return HideDropdownAttribute_Class;
}

MonoClass* FReflectionRegistry::GetShowCategoriesAttribute_Class() const
{
	return ShowCategoriesAttribute_Class;
}

MonoClass* FReflectionRegistry::GetComponentWrapperClassAttribute_Class() const
{
	return ComponentWrapperClassAttribute_Class;
}

MonoClass* FReflectionRegistry::GetHideFunctionsAttribute_Class() const
{
	return HideFunctionsAttribute_Class;
}

MonoClass* FReflectionRegistry::GetAutoExpandCategoriesAttribute_Class() const
{
	return AutoExpandCategoriesAttribute_Class;
}

MonoClass* FReflectionRegistry::GetAutoCollapseCategoriesAttribute_Class() const
{
	return AutoCollapseCategoriesAttribute_Class;
}

MonoClass* FReflectionRegistry::GetCollapseCategoriesAttribute_Class() const
{
	return CollapseCategoriesAttribute_Class;
}

MonoClass* FReflectionRegistry::GetDontCollapseCategoriesAttribute_Class() const
{
	return DontCollapseCategoriesAttribute_Class;
}

MonoClass* FReflectionRegistry::GetPrioritizeCategoriesAttribute_Class() const
{
	return PrioritizeCategoriesAttribute_Class;
}

MonoClass* FReflectionRegistry::GetAdvancedClassDisplayAttribute_Class() const
{
	return AdvancedClassDisplayAttribute_Class;
}

MonoClass* FReflectionRegistry::GetEarlyAccessPreviewAttribute_Class() const
{
	return EarlyAccessPreviewAttribute_Class;
}

MonoClass* FReflectionRegistry::GetSparseClassDataTypeAttribute_Class() const
{
	return SparseClassDataTypeAttribute_Class;
}

MonoClass* FReflectionRegistry::GetGlobalConfigAttribute_Class() const
{
	return GlobalConfigAttribute_Class;
}

MonoClass* FReflectionRegistry::GetLocalizedAttribute_Class() const
{
	return LocalizedAttribute_Class;
}

MonoClass* FReflectionRegistry::GetDuplicateTransientAttribute_Class() const
{
	return DuplicateTransientAttribute_Class;
}

MonoClass* FReflectionRegistry::GetNonPIETransientAttribute_Class() const
{
	return NonPIETransientAttribute_Class;
}

MonoClass* FReflectionRegistry::GetNonPIEDuplicateTransientAttribute_Class() const
{
	return NonPIEDuplicateTransientAttribute_Class;
}

MonoClass* FReflectionRegistry::GetExportAttribute_Class() const
{
	return ExportAttribute_Class;
}

MonoClass* FReflectionRegistry::GetNoClearAttribute_Class() const
{
	return NoClearAttribute_Class;
}

MonoClass* FReflectionRegistry::GetEditFixedSizeAttribute_Class() const
{
	return EditFixedSizeAttribute_Class;
}

MonoClass* FReflectionRegistry::GetReplicatedAttribute_Class() const
{
	return ReplicatedAttribute_Class;
}

MonoClass* FReflectionRegistry::GetReplicatedUsingAttribute_Class() const
{
	return ReplicatedUsingAttribute_Class;
}

MonoClass* FReflectionRegistry::GetNotReplicatedAttribute_Class() const
{
	return NotReplicatedAttribute_Class;
}

MonoClass* FReflectionRegistry::GetInterpAttribute_Class() const
{
	return InterpAttribute_Class;
}

MonoClass* FReflectionRegistry::GetNonTransactionalAttribute_Class() const
{
	return NonTransactionalAttribute_Class;
}

MonoClass* FReflectionRegistry::GetInstancedAttribute_Class() const
{
	return InstancedAttribute_Class;
}

MonoClass* FReflectionRegistry::GetBlueprintAssignableAttribute_Class() const
{
	return BlueprintAssignableAttribute_Class;
}

MonoClass* FReflectionRegistry::GetSimpleDisplayAttribute_Class() const
{
	return SimpleDisplayAttribute_Class;
}

MonoClass* FReflectionRegistry::GetAdvancedDisplayAttribute_Class() const
{
	return AdvancedDisplayAttribute_Class;
}

MonoClass* FReflectionRegistry::GetEditAnywhereAttribute_Class() const
{
	return EditAnywhereAttribute_Class;
}

MonoClass* FReflectionRegistry::GetEditInstanceOnlyAttribute_Class() const
{
	return EditInstanceOnlyAttribute_Class;
}

MonoClass* FReflectionRegistry::GetEditDefaultsOnlyAttribute_Class() const
{
	return EditDefaultsOnlyAttribute_Class;
}

MonoClass* FReflectionRegistry::GetVisibleAnywhereAttribute_Class() const
{
	return VisibleAnywhereAttribute_Class;
}

MonoClass* FReflectionRegistry::GetVisibleDefaultsOnlyAttribute_Class() const
{
	return VisibleDefaultsOnlyAttribute_Class;
}

MonoClass* FReflectionRegistry::GetBlueprintReadOnlyAttribute_Class() const
{
	return BlueprintReadOnlyAttribute_Class;
}

MonoClass* FReflectionRegistry::GetBlueprintReadWriteAttribute_Class() const
{
	return BlueprintReadWriteAttribute_Class;
}

MonoClass* FReflectionRegistry::GetAssetRegistrySearchableAttribute_Class() const
{
	return AssetRegistrySearchableAttribute_Class;
}

MonoClass* FReflectionRegistry::GetSaveGameAttribute_Class() const
{
	return SaveGameAttribute_Class;
}

MonoClass* FReflectionRegistry::GetTextExportTransientAttribute_Class() const
{
	return TextExportTransientAttribute_Class;
}

MonoClass* FReflectionRegistry::GetSkipSerializationAttribute_Class() const
{
	return SkipSerializationAttribute_Class;
}

MonoClass* FReflectionRegistry::GetDefaultSubObjectAttribute_Class() const
{
	return DefaultSubObjectAttribute_Class;
}

MonoClass* FReflectionRegistry::GetRootComponentAttribute_Class() const
{
	return RootComponentAttribute_Class;
}

MonoClass* FReflectionRegistry::GetAttachmentParentAttribute_Class() const
{
	return AttachmentParentAttribute_Class;
}

MonoClass* FReflectionRegistry::GetAttachmentSocketNameAttribute_Class() const
{
	return AttachmentSocketNameAttribute_Class;
}

MonoClass* FReflectionRegistry::GetDefaultValueAttribute_Class() const
{
	return DefaultValueAttribute_Class;
}

MonoClass* FReflectionRegistry::GetBlueprintImplementableEventAttribute_Class() const
{
	return BlueprintImplementableEventAttribute_Class;
}

MonoClass* FReflectionRegistry::GetBlueprintNativeEventAttribute_Class() const
{
	return BlueprintNativeEventAttribute_Class;
}

MonoClass* FReflectionRegistry::GetSealedEventAttribute_Class() const
{
	return SealedEventAttribute_Class;
}

MonoClass* FReflectionRegistry::GetExecAttribute_Class() const
{
	return ExecAttribute_Class;
}

MonoClass* FReflectionRegistry::GetServerAttribute_Class() const
{
	return ServerAttribute_Class;
}

MonoClass* FReflectionRegistry::GetClientAttribute_Class() const
{
	return ClientAttribute_Class;
}

MonoClass* FReflectionRegistry::GetNetMulticastAttribute_Class() const
{
	return NetMulticastAttribute_Class;
}

MonoClass* FReflectionRegistry::GetReliableAttribute_Class() const
{
	return ReliableAttribute_Class;
}

MonoClass* FReflectionRegistry::GetUnreliableAttribute_Class() const
{
	return UnreliableAttribute_Class;
}

MonoClass* FReflectionRegistry::GetBlueprintPureAttribute_Class() const
{
	return BlueprintPureAttribute_Class;
}

MonoClass* FReflectionRegistry::GetBlueprintCosmeticAttribute_Class() const
{
	return BlueprintCosmeticAttribute_Class;
}

MonoClass* FReflectionRegistry::GetCustomThunkAttribute_Class() const
{
	return CustomThunkAttribute_Class;
}

MonoClass* FReflectionRegistry::GetWithValidationAttribute_Class() const
{
	return WithinAttribute_Class;
}

MonoClass* FReflectionRegistry::GetServiceRequestAttribute_Class() const
{
	return ServiceRequestAttribute_Class;
}

MonoClass* FReflectionRegistry::GetServiceResponseAttribute_Class() const
{
	return ServiceResponseAttribute_Class;
}

FClassReflection* FReflectionRegistry::Get_Utils_Class() const
{
	return Utils_Class;
}

// MetaDataAttributeMacro.h - 按顺序添加的 getter 实现
#if WITH_EDITOR
FClassReflection* FReflectionRegistry::GetHideCategoriesAttribute_Class() const
{
	return HideCategoriesAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetConversionRootAttribute_Class() const
{
	return ConversionRootAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetCannotImplementInterfaceInBlueprintAttribute_Class() const
{
	return CannotImplementInterfaceInBlueprintAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetToolTipAttribute_Class() const
{
	return ToolTipAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetShortTooltipAttribute_Class() const
{
	return ShortTooltipAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetDocumentationPolicyAttribute_Class() const
{
	return DocumentationPolicyAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetBlueprintSpawnableComponentAttribute_Class() const
{
	return BlueprintSpawnableComponentAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetChildCanTickAttribute_Class() const
{
	return ChildCanTickAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetChildCannotTickAttribute_Class() const
{
	return ChildCannotTickAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetDebugTreeLeafAttribute_Class() const
{
	return DebugTreeLeafAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetIgnoreCategoryKeywordsInSubclassesAttribute_Class() const
{
	return IgnoreCategoryKeywordsInSubclassesAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetDeprecatedNodeAttribute_Class() const
{
	return DeprecatedNodeAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetDeprecationMessageAttribute_Class() const
{
	return DeprecationMessageAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetDisplayNameAttribute_Class() const
{
	return DisplayNameAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetScriptNameAttribute_Class() const
{
	return ScriptNameAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetIsBlueprintBaseAttribute_Class() const
{
	return IsBlueprintBaseAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetKismetHideOverridesAttribute_Class() const
{
	return KismetHideOverridesAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetLoadBehaviorAttribute_Class() const
{
	return LoadBehaviorAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetProhibitedInterfacesAttribute_Class() const
{
	return ProhibitedInterfacesAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetRestrictedToClassesAttribute_Class() const
{
	return RestrictedToClassesAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetShowWorldContextPinAttribute_Class() const
{
	return ShowWorldContextPinAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetDontUseGenericSpawnObjectAttribute_Class() const
{
	return DontUseGenericSpawnObjectAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetExposedAsyncProxyAttribute_Class() const
{
	return ExposedAsyncProxyAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetBlueprintThreadSafeAttribute_Class() const
{
	return BlueprintThreadSafeAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetUsesHierarchyAttribute_Class() const
{
	return UsesHierarchyAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetHasNativeBreakAttribute_Class() const
{
	return HasNativeBreakAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetHasNativeMakeAttribute_Class() const
{
	return HasNativeMakeAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetHiddenByDefaultAttribute_Class() const
{
	return HiddenByDefaultAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetDisableSplitPinAttribute_Class() const
{
	return DisableSplitPinAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetAllowAbstractAttribute_Class() const
{
	return AllowAbstractAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetAllowAnyActorAttribute_Class() const
{
	return AllowAnyActorAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetAllowedClassesAttribute_Class() const
{
	return AllowedClassesAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetAllowPreserveRatioAttribute_Class() const
{
	return AllowPreserveRatioAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetAllowPrivateAccessAttribute_Class() const
{
	return AllowPrivateAccessAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetArrayClampAttribute_Class() const
{
	return ArrayClampAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetAssetBundlesAttribute_Class() const
{
	return AssetBundlesAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetBlueprintBaseOnlyAttribute_Class() const
{
	return BlueprintBaseOnlyAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetBlueprintCompilerGeneratedDefaultsAttribute_Class() const
{
	return BlueprintCompilerGeneratedDefaultsAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetClampMinAttribute_Class() const
{
	return ClampMinAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetClampMaxAttribute_Class() const
{
	return ClampMaxAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetConfigHierarchyEditableAttribute_Class() const
{
	return ConfigHierarchyEditableAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetContentDirAttribute_Class() const
{
	return ContentDirAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetDeltaAttribute_Class() const
{
	return DeltaAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetDeprecatedPropertyAttribute_Class() const
{
	return DeprecatedPropertyAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetDisallowedAssetDataTagsAttribute_Class() const
{
	return DisallowedAssetDataTagsAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetDisallowedClassesAttribute_Class() const
{
	return DisallowedClassesAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetDisplayAfterAttribute_Class() const
{
	return DisplayAfterAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetDisplayPriorityAttribute_Class() const
{
	return DisplayPriorityAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetDisplayThumbnailAttribute_Class() const
{
	return DisplayThumbnailAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetEditConditionAttribute_Class() const
{
	return EditConditionAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetEditConditionHidesAttribute_Class() const
{
	return EditConditionHidesAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetEditFixedOrderAttribute_Class() const
{
	return EditFixedOrderAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetCategoryAttribute_Class() const
{
	return CategoryAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetExactClassAttribute_Class() const
{
	return ExactClassAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetExposeFunctionCategoriesAttribute_Class() const
{
	return ExposeFunctionCategoriesAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetExposeOnSpawnAttribute_Class() const
{
	return ExposeOnSpawnAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetFilePathFilterAttribute_Class() const
{
	return FilePathFilterAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetRelativeToGameDirAttribute_Class() const
{
	return RelativeToGameDirAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetFixedIncrementAttribute_Class() const
{
	return FixedIncrementAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetForceShowEngineContentAttribute_Class() const
{
	return ForceShowEngineContentAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetForceShowPluginContentAttribute_Class() const
{
	return ForceShowPluginContentAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetHideAlphaChannelAttribute_Class() const
{
	return HideAlphaChannelAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetHideInDetailPanelAttribute_Class() const
{
	return HideInDetailPanelAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetHideViewOptionsAttribute_Class() const
{
	return HideViewOptionsAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetIgnoreForMemberInitializationTestAttribute_Class() const
{
	return IgnoreForMemberInitializationTestAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetInlineEditConditionToggleAttribute_Class() const
{
	return InlineEditConditionToggleAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetLinearDeltaSensitivityAttribute_Class() const
{
	return LinearDeltaSensitivityAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetLongPackageNameAttribute_Class() const
{
	return LongPackageNameAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetMakeEditWidgetAttribute_Class() const
{
	return MakeEditWidgetAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetMakeStructureDefaultValueAttribute_Class() const
{
	return MakeStructureDefaultValueAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetMetaClassAttribute_Class() const
{
	return MetaClassAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetMustImplementAttribute_Class() const
{
	return MustImplementAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetMultipleAttribute_Class() const
{
	return MultipleAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetMaxLengthAttribute_Class() const
{
	return MaxLengthAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetMultiLineAttribute_Class() const
{
	return MultiLineAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetPasswordFieldAttribute_Class() const
{
	return PasswordFieldAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetNoElementDuplicateAttribute_Class() const
{
	return NoElementDuplicateAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetNoResetToDefaultAttribute_Class() const
{
	return NoResetToDefaultAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetEditInlineAttribute_Class() const
{
	return EditInlineAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetNoEditInlineAttribute_Class() const
{
	return NoEditInlineAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetNoSpinboxAttribute_Class() const
{
	return NoSpinboxAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetOnlyPlaceableAttribute_Class() const
{
	return OnlyPlaceableAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetRelativePathAttribute_Class() const
{
	return RelativePathAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetRelativeToGameContentDirAttribute_Class() const
{
	return RelativeToGameContentDirAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetRequiredAssetDataTagsAttribute_Class() const
{
	return RequiredAssetDataTagsAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetScriptNoExportAttribute_Class() const
{
	return ScriptNoExportAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetShowOnlyInnerPropertiesAttribute_Class() const
{
	return ShowOnlyInnerPropertiesAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetShowTreeViewAttribute_Class() const
{
	return ShowTreeViewAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetSliderExponentAttribute_Class() const
{
	return SliderExponentAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetTitlePropertyAttribute_Class() const
{
	return TitlePropertyAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetUIMinAttribute_Class() const
{
	return UIMinAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetUIMaxAttribute_Class() const
{
	return UIMaxAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetUnitsAttribute_Class() const
{
	return UnitsAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetForceUnitsAttribute_Class() const
{
	return ForceUnitsAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetUntrackedAttribute_Class() const
{
	return UntrackedAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetDevelopmentOnlyAttribute_Class() const
{
	return DevelopmentOnlyAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetNeedsLatentFixupAttribute_Class() const
{
	return NeedsLatentFixupAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetLatentCallbackTargetAttribute_Class() const
{
	return LatentCallbackTargetAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetGetOptionsAttribute_Class() const
{
	return GetOptionsAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetPinHiddenByDefaultAttribute_Class() const
{
	return PinHiddenByDefaultAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetValidEnumValuesAttribute_Class() const
{
	return ValidEnumValuesAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetInvalidEnumValuesAttribute_Class() const
{
	return InvalidEnumValuesAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetOverridingInputPropertyAttribute_Class() const
{
	return OverridingInputPropertyAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetRequiredInputAttribute_Class() const
{
	return RequiredInputAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetNeverAsPinAttribute_Class() const
{
	return NeverAsPinAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetPinShownByDefaultAttribute_Class() const
{
	return PinShownByDefaultAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetAlwaysAsPinAttribute_Class() const
{
	return AlwaysAsPinAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetCustomizePropertyAttribute_Class() const
{
	return CustomizePropertyAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetCallInEditorAttribute_Class() const
{
	return CallInEditorAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetVariadicAttribute_Class() const
{
	return VariadicAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetReturnDisplayNameAttribute_Class() const
{
	return ReturnDisplayNameAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetInternalUseParamAttribute_Class() const
{
	return InternalUseParamAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetForceAsFunctionAttribute_Class() const
{
	return ForceAsFunctionAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetIgnoreTypePromotionAttribute_Class() const
{
	return IgnoreTypePromotionAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetArrayParmAttribute_Class() const
{
	return ArrayParmAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetArrayTypeDependentParamsAttribute_Class() const
{
	return ArrayTypeDependentParamsAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetAutoCreateRefTermAttribute_Class() const
{
	return AutoCreateRefTermAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetHideAssetPickerAttribute_Class() const
{
	return HideAssetPickerAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetBlueprintInternalUseOnlyAttribute_Class() const
{
	return BlueprintInternalUseOnlyAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetBlueprintProtectedAttribute_Class() const
{
	return BlueprintProtectedAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetCallableWithoutWorldContextAttribute_Class() const
{
	return CallableWithoutWorldContextAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetCommutativeAssociativeBinaryOperatorAttribute_Class() const
{
	return CommutativeAssociativeBinaryOperatorAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetCompactNodeTitleAttribute_Class() const
{
	return CompactNodeTitleAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetCustomStructureParamAttribute_Class() const
{
	return CustomStructureParamAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetDefaultToSelfAttribute_Class() const
{
	return DefaultToSelfAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetDeprecatedFunctionAttribute_Class() const
{
	return DeprecatedFunctionAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetExpandEnumAsExecsAttribute_Class() const
{
	return ExpandEnumAsExecsAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetExpandBoolAsExecsAttribute_Class() const
{
	return ExpandBoolAsExecsAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetScriptMethodAttribute_Class() const
{
	return ScriptMethodAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetScriptMethodSelfReturnAttribute_Class() const
{
	return ScriptMethodSelfReturnAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetScriptOperatorAttribute_Class() const
{
	return ScriptOperatorAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetScriptConstantAttribute_Class() const
{
	return ScriptConstantAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetScriptConstantHostAttribute_Class() const
{
	return ScriptConstantHostAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetHidePinAttribute_Class() const
{
	return HidePinAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetHideSpawnParmsAttribute_Class() const
{
	return HideSpawnParmsAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetKeywordsAttribute_Class() const
{
	return KeywordsAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetLatentAttribute_Class() const
{
	return LatentAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetLatentInfoAttribute_Class() const
{
	return LatentInfoAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetMaterialParameterCollectionFunctionAttribute_Class() const
{
	return MaterialParameterCollectionFunctionAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetNativeBreakFuncAttribute_Class() const
{
	return NativeBreakFuncAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetNativeMakeFuncAttribute_Class() const
{
	return NativeMakeFuncAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetUnsafeDuringActorConstructionAttribute_Class() const
{
	return UnsafeDuringActorConstructionAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetWorldContextAttribute_Class() const
{
	return WorldContextAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetBlueprintAutoCastAttribute_Class() const
{
	return BlueprintAutoCastAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetNotBlueprintThreadSafeAttribute_Class() const
{
	return NotBlueprintThreadSafeAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetDeterminesOutputTypeAttribute_Class() const
{
	return DeterminesOutputTypeAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetDynamicOutputParamAttribute_Class() const
{
	return DynamicOutputParamAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetDataTablePinAttribute_Class() const
{
	return DataTablePinAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetSetParamAttribute_Class() const
{
	return SetParamAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetMapParamAttribute_Class() const
{
	return MapParamAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetMapKeyParamAttribute_Class() const
{
	return MapKeyParamAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetMapValueParamAttribute_Class() const
{
	return MapValueParamAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetBitmaskAttribute_Class() const
{
	return BitmaskAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetBitmaskEnumAttribute_Class() const
{
	return BitmaskEnumAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetBitflagsAttribute_Class() const
{
	return BitflagsAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetUseEnumValuesAsMaskValuesInEditorAttribute_Class() const
{
	return UseEnumValuesAsMaskValuesInEditorAttribute_Class;
}

FClassReflection* FReflectionRegistry::GetArrayParamAttribute_Class() const
{
	return ArrayParamAttribute_Class;
}
#endif

void FReflectionRegistry::Reset()
{
	ClassReflection.Empty();
	
	ClassReflection1.Empty();
}
