#include "Reflection/FReflectionRegistry.h"
#include "CoreMacro/GenericAttributeMacro.h"
#include "CoreMacro/ClassAttributeMacro.h"
#include "CoreMacro/PropertyAttributeMacro.h"
#include "CoreMacro/FunctionAttributeMacro.h"
#include "CoreMacro/MetaDataAttributeMacro.h"

FReflectionRegistry& FReflectionRegistry::Get()
{
	static FReflectionRegistry ReflectionRegistry;

	return ReflectionRegistry;
}

FReflectionRegistry::FReflectionRegistry()
{
}

void FReflectionRegistry::Initialize()
{
	UtilsClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_CORE_UOBJECT), CLASS_UTILS);

	ByteClass = GetClass(FMonoDomain::Get_Byte_Class());

	ObjectClass = GetClass(FMonoDomain::Get_Object_Class());

	UInt16Class = GetClass(FMonoDomain::Get_UInt16_Class());

	UInt32Class = GetClass(FMonoDomain::Get_UInt32_Class());

	UInt64Class = GetClass(FMonoDomain::Get_UInt64_Class());

	SByteClass = GetClass(FMonoDomain::Get_SByte_Class());

	Int16Class = GetClass(FMonoDomain::Get_Int16_Class());

	Int32Class = GetClass(FMonoDomain::Get_Int32_Class());

	Int64Class = GetClass(FMonoDomain::Get_Int64_Class());

	BooleanClass = GetClass(FMonoDomain::Get_Boolean_Class());

	SingleClass = GetClass(FMonoDomain::Get_Single_Class());

	EnumClass = GetClass(FMonoDomain::Get_Enum_Class());

	DoubleClass = GetClass(FMonoDomain::Get_Double_Class());

	UClassClass = GetClass(UClass::StaticClass());

	TSubclassOfClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_CORE_UOBJECT), GENERIC_T_SUB_CLASS_OF);

	UObjectClass = GetClass(UObject::StaticClass());

	NameClass = GetClass<FName>();

	TScriptInterfaceClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_CORE_UOBJECT), GENERIC_T_SCRIPT_INTERFACE);

	StringClass = GetClass<FString>();

#if UE_F_UTF8_STR_PROPERTY
	Utf8StringClass = GetClass<FUtf8String>();
#endif

#if UE_F_ANSI_STR_PROPERTY
	AnsiStringClass = GetClass<FAnsiString>();
#endif

	TextClass = GetClass<FText>();

	TWeakObjectPtrClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_CORE_UOBJECT), GENERIC_T_WEAK_OBJECT_PTR);

	TLazyObjectPtrClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_CORE_UOBJECT), GENERIC_T_LAZY_OBJECT_PTR);

	TSoftClassPtrClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_CORE_UOBJECT), GENERIC_T_SOFT_CLASS_PTR);

	TSoftObjectPtrClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_CORE_UOBJECT), GENERIC_T_SOFT_OBJECT_PTR);

	TMapClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_CORE_UOBJECT), GENERIC_T_MAP);

	TSetClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_CORE_UOBJECT), GENERIC_T_SET);

	TArrayClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_CORE_UOBJECT), GENERIC_T_ARRAY);

#if UE_F_OPTIONAL_PROPERTY
	TOptionalClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_CORE_UOBJECT), GENERIC_T_OPTIONAL);
#endif

	OverrideAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_CORE_UOBJECT), CLASS_OVERRIDE_ATTRIBUTE);

	UClassAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_U_CLASS_ATTRIBUTE);

	UStructAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_U_STRUCT_ATTRIBUTE);

	UEnumAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_U_ENUM_ATTRIBUTE);

	UPropertyAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_U_PROPERTY_ATTRIBUTE);

	UFunctionAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_U_FUNCTION_ATTRIBUTE);

	UInterfaceAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_U_INTERFACE_ATTRIBUTE);

	VisibleInstanceOnlyAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_VISIBLE_INSTANCE_ONLY_ATTRIBUTE);

	BlueprintCallableAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_CALLABLE_ATTRIBUTE);

	BlueprintAuthorityOnlyAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_AUTHORITY_ONLY_ATTRIBUTE);

	BlueprintGetterAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_GETTER_ATTRIBUTE);

	BlueprintSetterAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_SETTER_ATTRIBUTE);

	FieldNotifyAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_FIELD_NOTIFY_ATTRIBUTE);

	TransientAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_TRANSIENT_ATTRIBUTE);

	ConfigAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CONFIG_ATTRIBUTE);

	BlueprintTypeAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_TYPE_ATTRIBUTE);

	NotBlueprintTypeAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NOT_BLUEPRINT_TYPE_ATTRIBUTE);

	BlueprintableAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINTABLE_ATTRIBUTE);

	NotBlueprintableAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NOT_BLUEPRINTABLE_ATTRIBUTE);

	NoExportAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NO_EXPORT_ATTRIBUTE);

	AbstractAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ABSTRACT_ATTRIBUTE);

	ExperimentalAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EXPERIMENTAL_ATTRIBUTE);

	EditorConfigAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EDITOR_CONFIG_ATTRIBUTE);

	ClassGroupAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CLASS_GROUP_ATTRIBUTE);

	WithinAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_WITHIN_ATTRIBUTE);

	MinimalAPIAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_MINIMAL_API_ATTRIBUTE);

	CustomConstructorAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CUSTOM_CONSTRUCTOR_ATTRIBUTE);

	IntrinsicAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_INTRINSIC_ATTRIBUTE);

	NotPlaceableAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NOT_PLACEABLE_ATTRIBUTE);

	DefaultToInstancedAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DEFAULT_TO_INSTANCED_ATTRIBUTE);

	ConstAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CONST_ATTRIBUTE);

	DeprecatedAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DEPRECATED_ATTRIBUTE);

	PerObjectConfigAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_PER_OBJECT_CONFIG_ATTRIBUTE);

	ConfigDoNotCheckDefaultsAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CONFIG_DO_NOT_CHECK_DEFAULTS_ATTRIBUTE);

	DefaultConfigAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DEFAULT_CONFIG_ATTRIBUTE);

	EditInlineNewAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EDIT_INLINE_NEW_ATTRIBUTE);

	NotEditInlineNewAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NOT_EDIT_INLINE_NEW_ATTRIBUTE);

	HideDropdownAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_HIDE_DROP_DOWN_ATTRIBUTE);

	ShowCategoriesAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SHOW_CATEGORIES_ATTRIBUTE);

	ComponentWrapperClassAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_COMPONENT_WRAPPER_CLASS_ATTRIBUTE);

	HideFunctionsAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_HIDE_FUNCTIONS_ATTRIBUTE);

	AutoExpandCategoriesAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_AUTO_EXPAND_CATEGORIES_ATTRIBUTE);

	AutoCollapseCategoriesAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_AUTO_COLLAPSE_CATEGORIES_ATTRIBUTE);

	CollapseCategoriesAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_COLLAPSE_CATEGORIES_ATTRIBUTE);

	DontCollapseCategoriesAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DONT_COLLAPSE_CATEGORIES_ATTRIBUTE);

	PrioritizeCategoriesAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_PRIORITIZE_CATEGORIES_ATTRIBUTE);

	AdvancedClassDisplayAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ADVANCED_CLASS_DISPLAY_ATTRIBUTE);

	EarlyAccessPreviewAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EARLY_ACCESS_PREVIEW_ATTRIBUTE);

	SparseClassDataTypeAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SPARSE_CLASS_DATA_TYPE_ATTRIBUTE);

	GlobalConfigAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_GLOBAL_CONFIG_ATTRIBUTE);

	LocalizedAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_LOCALIZED_ATTRIBUTE);

	DuplicateTransientAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DUPLICATE_TRANSIENT_ATTRIBUTE);

	NonPIETransientAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NON_PIE_TRANSIENT_ATTRIBUTE);

	NonPIEDuplicateTransientAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NON_PIE_DUPLICATE_TRANSIENT_ATTRIBUTE);

	ExportAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EXPORT_ATTRIBUTE);

	NoClearAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NO_CLEAR_ATTRIBUTE);

	EditFixedSizeAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EDIT_FIXED_SIZE_ATTRIBUTE);

	ReplicatedAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_REPLICATED_ATTRIBUTE);

	ReplicatedUsingAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_REPLICATED_USING_ATTRIBUTE);

	NotReplicatedAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NOT_REPLICATED_ATTRIBUTE);

	InterpAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_INTERP_ATTRIBUTE);

	NonTransactionalAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NON_TRANSACTIONAL_ATTRIBUTE);

	InstancedAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_INSTANCED_ATTRIBUTE);

	BlueprintAssignableAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_ASSIGNABLE_ATTRIBUTE);

	SimpleDisplayAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SIMPLE_DISPLAY_ATTRIBUTE);

	AdvancedDisplayAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ADVANCED_DISPLAY_ATTRIBUTE);

	EditAnywhereAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EDIT_ANYWHERE_ATTRIBUTE);

	EditInstanceOnlyAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EDIT_INSTANCE_ONLY_ATTRIBUTE);

	EditDefaultsOnlyAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EDIT_DEFAULTS_ONLY_ATTRIBUTE);

	VisibleAnywhereAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_VISIBLE_ANYWHERE_ATTRIBUTE);

	VisibleDefaultsOnlyAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_VISIBLE_DEFAULTS_ONLY_ATTRIBUTE);

	BlueprintReadOnlyAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_READ_ONLY_ATTRIBUTE);

	BlueprintReadWriteAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_READ_WRITE_ATTRIBUTE);

	AssetRegistrySearchableAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ASSET_REGISTRY_SEARCHABLE_ATTRIBUTE);

	SaveGameAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SAVE_GAME_ATTRIBUTE);

	TextExportTransientAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_TEXT_EXPORT_TRANSIENT_ATTRIBUTE);

	SkipSerializationAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SKIP_SERIALIZATION_ATTRIBUTE);

	DefaultSubObjectAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DEFAULT_SUB_OBJECT_ATTRIBUTE);

	RootComponentAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ROOT_COMPONENT_ATTRIBUTE);

	AttachmentParentAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ATTACHMENT_PARENT_ATTRIBUTE);

	AttachmentSocketNameAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ATTACHMENT_SOCKET_NAME_ATTRIBUTE);

	DefaultValueAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DEFAULT_VALUE_ATTRIBUTE);

	BlueprintImplementableEventAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_IMPLEMENTABLE_EVENT_ATTRIBUTE);

	BlueprintNativeEventAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_NATIVE_EVENT_ATTRIBUTE);

	SealedEventAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SEALED_EVENT_ATTRIBUTE);

	ExecAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EXEC_ATTRIBUTE);

	ServerAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SERVER_ATTRIBUTE);

	ClientAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CLIENT_ATTRIBUTE);

	NetMulticastAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NET_MULTICAST_ATTRIBUTE);

	ReliableAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_RELIABLE_ATTRIBUTE);

	UnreliableAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_UNRELIABLE_ATTRIBUTE);

	BlueprintPureAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_PURE_ATTRIBUTE);

	BlueprintCosmeticAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_COSMETIC_ATTRIBUTE);

	CustomThunkAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CUSTOM_THUNK_ATTRIBUTE);

	WithValidationAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_WITH_VALIDATION_ATTRIBUTE);

	ServiceRequestAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SERVICE_REQUEST_ATTRIBUTE);

	ServiceResponseAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SERVICE_RESPONSE_ATTRIBUTE);

#if WITH_EDITOR
	HideCategoriesAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_HIDE_CATEGORIES_ATTRIBUTE);

	ConversionRootAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CONVERSION_ROOT_ATTRIBUTE);

	CannotImplementInterfaceInBlueprintAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CANNOT_IMPLEMENT_INTERFACE_IN_BLUEPRINT_ATTRIBUTE);

	ToolTipAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_TOOLTIP_ATTRIBUTE);

	ShortTooltipAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SHORT_TOOLTIP_ATTRIBUTE);

	DocumentationPolicyAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DOCUMENTATION_POLICY_ATTRIBUTE);

	BlueprintSpawnableComponentAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_SPAWNABLE_COMPONENT_ATTRIBUTE);

	ChildCanTickAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CHILD_CAN_TICK_ATTRIBUTE);

	ChildCannotTickAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CHILD_CANNOT_TICK_ATTRIBUTE);

	DebugTreeLeafAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DEBUG_TREE_LEAF_ATTRIBUTE);

	IgnoreCategoryKeywordsInSubclassesAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_IGNORE_CATEGORY_KEYWORDS_IN_SUBCLASSES_ATTRIBUTE);

	DeprecatedNodeAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DEPRECATED_NODE_ATTRIBUTE);

	DeprecationMessageAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DEPRECATION_MESSAGE_ATTRIBUTE);

	DisplayNameAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DISPLAY_NAME_ATTRIBUTE);

	ScriptNameAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SCRIPT_NAME_ATTRIBUTE);

	IsBlueprintBaseAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_IS_BLUEPRINT_BASE_ATTRIBUTE);

	KismetHideOverridesAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_KISMET_HIDE_OVERRIDES_ATTRIBUTE);

	LoadBehaviorAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_LOAD_BEHAVIOR_ATTRIBUTE);

	ProhibitedInterfacesAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_PROHIBITED_INTERFACES_ATTRIBUTE);

	RestrictedToClassesAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_RESTRICTED_TO_CLASSES_ATTRIBUTE);

	ShowWorldContextPinAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SHOW_WORLD_CONTEXT_PIN_ATTRIBUTE);

	DontUseGenericSpawnObjectAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DONT_USE_GENERIC_SPAWN_OBJECT_ATTRIBUTE);

	ExposedAsyncProxyAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EXPOSED_ASYNC_PROXY_ATTRIBUTE);

	BlueprintThreadSafeAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_THREAD_SAFE_ATTRIBUTE);

	UsesHierarchyAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_USES_HIERARCHY_ATTRIBUTE);

	HasNativeBreakAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_HAS_NATIVE_BREAK_ATTRIBUTE);

	HasNativeMakeAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_HAS_NATIVE_MAKE_ATTRIBUTE);

	HiddenByDefaultAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_HIDDEN_BY_DEFAULT_ATTRIBUTE);

	DisableSplitPinAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DISABLE_SPLIT_PIN_ATTRIBUTE);

	AllowAbstractAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ALLOW_ABSTRACT_ATTRIBUTE);

	AllowAnyActorAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ALLOW_ANY_ACTOR_ATTRIBUTE);

	AllowedClassesAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ALLOWED_CLASSES_ATTRIBUTE);

	AllowPreserveRatioAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ALLOW_PRESERVE_RATIO_ATTRIBUTE);

	AllowPrivateAccessAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ALLOW_PRIVATE_ACCESS_ATTRIBUTE);

	ArrayClampAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ARRAY_CLAMP_ATTRIBUTE);

	AssetBundlesAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ASSET_BUNDLES_ATTRIBUTE);

	BlueprintBaseOnlyAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_BASE_ONLY_ATTRIBUTE);

	BlueprintCompilerGeneratedDefaultsAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_COMPILER_GENERATED_DEFAULTS_ATTRIBUTE);

	ClampMinAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CLAMP_MIN_ATTRIBUTE);

	ClampMaxAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CLAMP_MAX_ATTRIBUTE);

	ConfigHierarchyEditableAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CONFIG_HIERARCHY_EDITABLE_ATTRIBUTE);

	ContentDirAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CONTENT_DIR_ATTRIBUTE);

	DeltaAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DELTA_ATTRIBUTE);

	DeprecatedPropertyAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DEPRECATED_PROPERTY_ATTRIBUTE);

	DisallowedAssetDataTagsAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DISALLOWED_ASSET_DATA_TAGS_ATTRIBUTE);

	DisallowedClassesAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DISALLOWED_CLASSES_ATTRIBUTE);

	DisplayAfterAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DISPLAY_AFTER_ATTRIBUTE);

	DisplayPriorityAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DISPLAY_PRIORITY_ATTRIBUTE);

	DisplayThumbnailAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DISPLAY_THUMBNAIL_ATTRIBUTE);

	EditConditionAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EDIT_CONDITION_ATTRIBUTE);

	EditConditionHidesAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EDIT_CONDITION_HIDES_ATTRIBUTE);

	EditFixedOrderAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EDIT_FIXED_ORDER_ATTRIBUTE);

	CategoryAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CATEGORY_ATTRIBUTE);

	ExactClassAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EXACT_CLASS_ATTRIBUTE);

	ExposeFunctionCategoriesAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EXPOSE_FUNCTION_CATEGORIES_ATTRIBUTE);

	ExposeOnSpawnAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EXPOSE_ON_SPAWN_ATTRIBUTE);

	FilePathFilterAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_FILE_PATH_FILTER_ATTRIBUTE);

	RelativeToGameDirAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_RELATIVE_TO_GAME_DIR_ATTRIBUTE);

	FixedIncrementAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_FIXED_INCREMENT_ATTRIBUTE);

	ForceShowEngineContentAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_FORCE_SHOW_ENGINE_CONTENT_ATTRIBUTE);

	ForceShowPluginContentAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_FORCE_SHOW_PLUGIN_CONTENT_ATTRIBUTE);

	HideAlphaChannelAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_HIDE_ALPHA_CHANNEL_ATTRIBUTE);

	HideInDetailPanelAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_HIDE_IN_DETAIL_PANEL_ATTRIBUTE);

	HideViewOptionsAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_HIDE_VIEW_OPTIONS_ATTRIBUTE);

	IgnoreForMemberInitializationTestAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_IGNORE_FOR_MEMBER_INITIALIZATION_TEST_ATTRIBUTE);

	InlineEditConditionToggleAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_INLINE_EDIT_CONDITION_TOGGLE_ATTRIBUTE);

	LinearDeltaSensitivityAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_LINEAR_DELTA_SENSITIVITY_ATTRIBUTE);

	LongPackageNameAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_LONG_PACKAGE_NAME_ATTRIBUTE);

	MakeEditWidgetAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_MAKE_EDIT_WIDGET_ATTRIBUTE);

	MakeStructureDefaultValueAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_MAKE_STRUCTURE_DEFAULT_VALUE_ATTRIBUTE);

	MetaClassAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_META_CLASS_ATTRIBUTE);

	MustImplementAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_MUST_IMPLEMENT_ATTRIBUTE);

	MultipleAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_MULTIPLE_ATTRIBUTE);

	MaxLengthAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_MAX_LENGTH_ATTRIBUTE);

	MultiLineAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_MULTILINE_ATTRIBUTE);

	PasswordFieldAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_PASSWORD_FIELD_ATTRIBUTE);

	NoElementDuplicateAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NO_ELEMENT_DUPLICATE_ATTRIBUTE);

	NoResetToDefaultAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NO_RESET_TO_DEFAULT_ATTRIBUTE);

	EditInlineAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EDIT_INLINE_ATTRIBUTE);

	NoEditInlineAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NO_EDIT_INLINE_ATTRIBUTE);

	NoSpinboxAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NO_SPIN_BOX_ATTRIBUTE);

	OnlyPlaceableAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ONLY_PLACEABLE_ATTRIBUTE);

	RelativePathAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_RELATIVE_PATH_ATTRIBUTE);

	RelativeToGameContentDirAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_RELATIVE_TO_GAME_CONTENT_DIR_ATTRIBUTE);

	RequiredAssetDataTagsAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_REQUIRED_ASSET_DATA_TAGS_ATTRIBUTE);

	ScriptNoExportAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SCRIPT_NO_EXPORT_ATTRIBUTE);

	ShowOnlyInnerPropertiesAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SHOW_ONLY_INNER_PROPERTIES_ATTRIBUTE);

	ShowTreeViewAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SHOW_TREE_VIEW_ATTRIBUTE);

	SliderExponentAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SLIDER_EXPONENT_ATTRIBUTE);

	TitlePropertyAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_TITLE_PROPERTY_ATTRIBUTE);

	UIMinAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_UI_MIN_ATTRIBUTE);

	UIMaxAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_UI_MAX_ATTRIBUTE);

	UnitsAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_UNITS_ATTRIBUTE);

	ForceUnitsAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_FORCE_UNITS_ATTRIBUTE);

	UntrackedAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_UNTRACKED_ATTRIBUTE);

	DevelopmentOnlyAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DEVELOPMENT_ONLY_ATTRIBUTE);

	NeedsLatentFixupAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NEEDS_LATENT_FIXUP_ATTRIBUTE);

	LatentCallbackTargetAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_LATENT_CALLBACK_TARGET_ATTRIBUTE);

	GetOptionsAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_GET_OPTIONS_ATTRIBUTE);

	PinHiddenByDefaultAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_PIN_HIDDEN_BY_DEFAULT_ATTRIBUTE);

	ValidEnumValuesAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_VALID_ENUM_VALUES_ATTRIBUTE);

	InvalidEnumValuesAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_INVALID_ENUM_VALUES_ATTRIBUTE);

	OverridingInputPropertyAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_OVERRIDING_INPUT_PROPERTY_ATTRIBUTE);

	RequiredInputAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_REQUIRED_INPUT_ATTRIBUTE);

	NeverAsPinAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NEVER_AS_PIN_ATTRIBUTE);

	PinShownByDefaultAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_PIN_SHOWN_BY_DEFAULT_ATTRIBUTE);

	AlwaysAsPinAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ALWAYS_AS_PIN_ATTRIBUTE);

	CustomizePropertyAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CUSTOMIZE_PROPERTY_ATTRIBUTE);

	CallInEditorAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CALL_IN_EDITOR_ATTRIBUTE);

	VariadicAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_VARIADIC_ATTRIBUTE);

	ReturnDisplayNameAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_RETURN_DISPLAY_NAME_ATTRIBUTE);

	InternalUseParamAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_INTERNAL_USE_PARAM_ATTRIBUTE);

	ForceAsFunctionAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_FORCE_AS_FUNCTION_ATTRIBUTE);

	IgnoreTypePromotionAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_IGNORE_TYPE_PROMOTION_ATTRIBUTE);

	ArrayParmAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ARRAY_PARM_ATTRIBUTE);

	ArrayTypeDependentParamsAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ARRAY_TYPE_DEPENDENT_PARAMS_ATTRIBUTE);

	AutoCreateRefTermAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_AUTO_CREATE_REF_TERM_ATTRIBUTE);

	HideAssetPickerAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_HIDE_ASSET_PICKER_ATTRIBUTE);

	BlueprintInternalUseOnlyAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_INTERNAL_USE_ONLY_ATTRIBUTE);

	BlueprintProtectedAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_PROTECTED_ATTRIBUTE);

	CallableWithoutWorldContextAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CALLABLE_WITHOUT_WORLD_CONTEXT_ATTRIBUTE);

	CommutativeAssociativeBinaryOperatorAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_COMMUTATIVE_ASSOCIATIVE_BINARY_OPERATOR_ATTRIBUTE);

	CompactNodeTitleAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_COMPACT_NODE_TITLE_ATTRIBUTE);

	CustomStructureParamAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_CUSTOM_STRUCTURE_PARAM_ATTRIBUTE);

	DefaultToSelfAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DEFAULT_TO_SELF_ATTRIBUTE);

	DeprecatedFunctionAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DEPRECATED_FUNCTION_ATTRIBUTE);

	ExpandEnumAsExecsAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EXPAND_ENUM_AS_EXECS_ATTRIBUTE);

	ExpandBoolAsExecsAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_EXPAND_BOOL_AS_EXECS_ATTRIBUTE);

	ScriptMethodAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SCRIPT_METHOD_ATTRIBUTE);

	ScriptMethodSelfReturnAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SCRIPT_METHOD_SELF_RETURN_ATTRIBUTE);

	ScriptOperatorAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SCRIPT_OPERATOR_ATTRIBUTE);

	ScriptConstantAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SCRIPT_CONSTANT_ATTRIBUTE);

	ScriptConstantHostAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SCRIPT_CONSTANT_HOST_ATTRIBUTE);

	HidePinAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_HIDE_PIN_ATTRIBUTE);

	HideSpawnParmsAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_HIDE_SPAWN_PARMS_ATTRIBUTE);

	KeywordsAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_KEYWORDS_ATTRIBUTE);

	LatentAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_LATENT_ATTRIBUTE);

	LatentInfoAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_LATENT_INFO_ATTRIBUTE);

	MaterialParameterCollectionFunctionAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_MATERIAL_PARAMETER_COLLECTION_FUNCTION_ATTRIBUTE);

	NativeBreakFuncAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NATIVE_BREAK_FUNC_ATTRIBUTE);

	NativeMakeFuncAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NATIVE_MAKE_FUNC_ATTRIBUTE);

	UnsafeDuringActorConstructionAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_UNSAFE_DURING_ACTOR_CONSTRUCTION_ATTRIBUTE);

	WorldContextAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_WORLD_CONTEXT_ATTRIBUTE);

	BlueprintAutoCastAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BLUEPRINT_AUTO_CAST_ATTRIBUTE);

	NotBlueprintThreadSafeAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_NOT_BLUEPRINT_THREAD_SAFE_ATTRIBUTE);

	DeterminesOutputTypeAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DETERMINES_OUTPUT_TYPE_ATTRIBUTE);

	DynamicOutputParamAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DYNAMIC_OUTPUT_PARAM_ATTRIBUTE);

	DataTablePinAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_DATA_TABLE_PIN_ATTRIBUTE);

	SetParamAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_SET_PARAM_ATTRIBUTE);

	MapParamAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_MAP_PARAM_ATTRIBUTE);

	MapKeyParamAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_MAP_KEY_PARAM_ATTRIBUTE);

	MapValueParamAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_MAP_VALUE_PARAM_ATTRIBUTE);

	BitmaskAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BIT_MASK_ATTRIBUTE);

	BitmaskEnumAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BIT_MASK_ENUM_ATTRIBUTE);

	BitflagsAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_BITFLAGS_ATTRIBUTE);

	UseEnumValuesAsMaskValuesInEditorAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_USE_ENUM_VALUES_AS_MASK_VALUES_IN_EDITOR);

	ArrayParamAttributeClass = GetClass(
		COMBINE_NAMESPACE(NAMESPACE_ROOT, NAMESPACE_DYNAMIC), CLASS_ARRAY_PARAM_ATTRIBUTE);
#endif
}

void FReflectionRegistry::Deinitialize()
{
	Field2Class.Empty();

	for (const auto& [PLACEHOLDER, Class] : Class2Class)
	{
		delete Class;
	}

	Class2Class.Empty();

	ReflectionType2Class.Empty();

	NameNameSpace2Class.Empty();
}

FClassReflection* FReflectionRegistry::GetClass(const TWeakObjectPtr<UField>& InField)
{
	if (const auto FoundClass = Field2Class.Find(InField))
	{
		return *FoundClass;
	}

	if (const auto FoundClass = GetMonoClass(InField))
	{
		const auto Class = new FClassReflection(FoundClass);

		Field2Class.Add(InField, Class);

		if (!Class2Class.Contains(FoundClass))
		{
			Class2Class.Add(FoundClass, Class);
		}

		if (!ReflectionType2Class.Contains(Class->GetReflectionType()))
		{
			ReflectionType2Class.Add(Class->GetReflectionType(), Class);
		}

		if (const auto Pair = TPair<FString, FString>(Class->GetNameSpace(), Class->GetName());
			!NameNameSpace2Class.Contains(Pair))
		{
			NameNameSpace2Class.Add(Pair, Class);
		}

		return Class;
	}

	return nullptr;
}

FClassReflection* FReflectionRegistry::GetClass(MonoReflectionType* InReflectionType)
{
	if (const auto FoundClass = ReflectionType2Class.Find(InReflectionType))
	{
		return *FoundClass;
	}

	const auto Class = new FClassReflection(InReflectionType);

	ReflectionType2Class.Add(InReflectionType, Class);

	if (!Class2Class.Contains(Class->GetClass()))
	{
		Class2Class.Add(Class->GetClass(), Class);
	}

	if (const auto Pair = TPair<FString, FString>(Class->GetNameSpace(), Class->GetName());
		!NameNameSpace2Class.Contains(Pair))
	{
		NameNameSpace2Class.Add(Pair, Class);
	}

	return Class;
}

FClassReflection* FReflectionRegistry::GetClass(MonoClass* InClass)
{
	if (const auto FoundClass = Class2Class.Find(InClass))
	{
		return *FoundClass;
	}

	const auto Class = new FClassReflection(InClass);

	Class2Class.Add(InClass, Class);

	if (!ReflectionType2Class.Contains(Class->GetReflectionType()))
	{
		ReflectionType2Class.Add(Class->GetReflectionType(), Class);
	}

	if (const auto Pair = TPair<FString, FString>(Class->GetNameSpace(), Class->GetName());
		!NameNameSpace2Class.Contains(Pair))
	{
		NameNameSpace2Class.Add(Pair, Class);
	}

	return Class;
}

FClassReflection* FReflectionRegistry::GetClass(const FString& InNameSpace, const FString& InName)
{
	const auto Pair = TPair<FString, FString>(InNameSpace, InName);

	if (const auto FoundClass = NameNameSpace2Class.Find(Pair))
	{
		return *FoundClass;
	}

	if (const auto FoundClass = FMonoDomain::Class_From_Name(InNameSpace, InName))
	{
		const auto Class = new FClassReflection(FoundClass, InName);

		NameNameSpace2Class.Add(Pair, Class);

		if (!Class2Class.Contains(Class->GetClass()))
		{
			Class2Class.Add(Class->GetClass(), Class);
		}

		if (!ReflectionType2Class.Contains(Class->GetReflectionType()))
		{
			ReflectionType2Class.Add(Class->GetReflectionType(), Class);
		}

		return Class;
	}

	return nullptr;
}

FClassReflection* FReflectionRegistry::GetUtilsClass() const
{
	return UtilsClass;
}

FClassReflection* FReflectionRegistry::GetByteClass() const
{
	return ByteClass;
}

FClassReflection* FReflectionRegistry::GetObjectClass() const
{
	return ObjectClass;
}

FClassReflection* FReflectionRegistry::GetUInt16Class() const
{
	return UInt16Class;
}

FClassReflection* FReflectionRegistry::GetUInt32Class() const
{
	return UInt32Class;
}

FClassReflection* FReflectionRegistry::GetUInt64Class() const
{
	return UInt64Class;
}

FClassReflection* FReflectionRegistry::GetSByteClass() const
{
	return SByteClass;
}

FClassReflection* FReflectionRegistry::GetInt16Class() const
{
	return Int16Class;
}

FClassReflection* FReflectionRegistry::GetInt32Class() const
{
	return Int32Class;
}

FClassReflection* FReflectionRegistry::GetInt64Class() const
{
	return Int64Class;
}

FClassReflection* FReflectionRegistry::GetBooleanClass() const
{
	return BooleanClass;
}

FClassReflection* FReflectionRegistry::GetSingleClass() const
{
	return SingleClass;
}

FClassReflection* FReflectionRegistry::GetEnumClass() const
{
	return EnumClass;
}

FClassReflection* FReflectionRegistry::GetDoubleClass() const
{
	return DoubleClass;
}

FClassReflection* FReflectionRegistry::GetUClassClass() const
{
	return UClassClass;
}

FClassReflection* FReflectionRegistry::GetUObjectClass() const
{
	return UObjectClass;
}

FClassReflection* FReflectionRegistry::GetTSubclassOfClass() const
{
	return TSubclassOfClass;
}

FClassReflection* FReflectionRegistry::GetNameClass() const
{
	return NameClass;
}

FClassReflection* FReflectionRegistry::GetTScriptInterfaceClass()
{
	return TScriptInterfaceClass;
}

FClassReflection* FReflectionRegistry::GetStringClass() const
{
	return StringClass;
}

#if UE_F_UTF8_STR_PROPERTY
FClassReflection* FReflectionRegistry::GetUtf8StringClass() const
{
	return Utf8StringClass;
}
#endif

#if UE_F_ANSI_STR_PROPERTY
FClassReflection* FReflectionRegistry::GetAnsiStringClass() const
{
	return AnsiStringClass;
}
#endif

FClassReflection* FReflectionRegistry::GetTextClass() const
{
	return TextClass;
}

FClassReflection* FReflectionRegistry::GetTWeakObjectPtrClass() const
{
	return TWeakObjectPtrClass;
}

FClassReflection* FReflectionRegistry::GetTLazyObjectPtrClass() const
{
	return TLazyObjectPtrClass;
}

FClassReflection* FReflectionRegistry::GetTSoftClassPtrClass() const
{
	return TSoftClassPtrClass;
}

FClassReflection* FReflectionRegistry::GetTSoftObjectPtrClass() const
{
	return TSoftObjectPtrClass;
}

FClassReflection* FReflectionRegistry::GetTMapClass() const
{
	return TMapClass;
}

FClassReflection* FReflectionRegistry::GetTSetClass() const
{
	return TSetClass;
}

FClassReflection* FReflectionRegistry::GetTArrayClass() const
{
	return TArrayClass;
}

#if UE_F_OPTIONAL_PROPERTY
FClassReflection* FReflectionRegistry::GetTOptionalClass() const
{
	return TOptionalClass;
}
#endif

FClassReflection* FReflectionRegistry::GetOverrideAttributeClass() const
{
	return OverrideAttributeClass;
}

FClassReflection* FReflectionRegistry::GetUClassAttributeClass() const
{
	return UClassAttributeClass;
}

FClassReflection* FReflectionRegistry::GetUStructAttributeClass() const
{
	return UStructAttributeClass;
}

FClassReflection* FReflectionRegistry::GetUEnumAttributeClass() const
{
	return UEnumAttributeClass;
}

FClassReflection* FReflectionRegistry::GetUInterfaceAttributeClass() const
{
	return UInterfaceAttributeClass;
}

FClassReflection* FReflectionRegistry::GetUPropertyAttributeClass() const
{
	return UPropertyAttributeClass;
}

FClassReflection* FReflectionRegistry::GetUFunctionAttributeClass() const
{
	return UFunctionAttributeClass;
}

FClassReflection* FReflectionRegistry::GetVisibleInstanceOnlyAttributeClass() const
{
	return VisibleInstanceOnlyAttributeClass;
}

FClassReflection* FReflectionRegistry::GetBlueprintCallableAttributeClass() const
{
	return BlueprintCallableAttributeClass;
}

FClassReflection* FReflectionRegistry::GetBlueprintAuthorityOnlyAttributeClass() const
{
	return BlueprintAuthorityOnlyAttributeClass;
}

FClassReflection* FReflectionRegistry::GetBlueprintGetterAttributeClass() const
{
	return BlueprintGetterAttributeClass;
}

FClassReflection* FReflectionRegistry::GetBlueprintSetterAttributeClass() const
{
	return BlueprintSetterAttributeClass;
}

FClassReflection* FReflectionRegistry::GetFieldNotifyAttributeClass() const
{
	return FieldNotifyAttributeClass;
}

FClassReflection* FReflectionRegistry::GetTransientAttributeClass() const
{
	return TransientAttributeClass;
}

FClassReflection* FReflectionRegistry::GetConfigAttributeClass() const
{
	return ConfigAttributeClass;
}

FClassReflection* FReflectionRegistry::GetBlueprintTypeAttributeClass() const
{
	return BlueprintTypeAttributeClass;
}

FClassReflection* FReflectionRegistry::GetNotBlueprintTypeAttributeClass() const
{
	return NotBlueprintTypeAttributeClass;
}

FClassReflection* FReflectionRegistry::GetBlueprintableAttributeClass() const
{
	return BlueprintableAttributeClass;
}

FClassReflection* FReflectionRegistry::GetNotBlueprintableAttributeClass() const
{
	return NotBlueprintableAttributeClass;
}

FClassReflection* FReflectionRegistry::GetNoExportAttributeClass() const
{
	return NoExportAttributeClass;
}

FClassReflection* FReflectionRegistry::GetAbstractAttributeClass() const
{
	return AbstractAttributeClass;
}

FClassReflection* FReflectionRegistry::GetExperimentalAttributeClass() const
{
	return ExperimentalAttributeClass;
}

FClassReflection* FReflectionRegistry::GetEditorConfigAttributeClass() const
{
	return EditorConfigAttributeClass;
}

FClassReflection* FReflectionRegistry::GetClassGroupAttributeClass() const
{
	return ClassGroupAttributeClass;
}

FClassReflection* FReflectionRegistry::GetWithinAttributeClass() const
{
	return WithinAttributeClass;
}

FClassReflection* FReflectionRegistry::GetMinimalAPIAttributeClass() const
{
	return MinimalAPIAttributeClass;
}

FClassReflection* FReflectionRegistry::GetCustomConstructorAttributeClass() const
{
	return CustomConstructorAttributeClass;
}

FClassReflection* FReflectionRegistry::GetIntrinsicAttributeClass() const
{
	return IntrinsicAttributeClass;
}

FClassReflection* FReflectionRegistry::GetNotPlaceableAttributeClass() const
{
	return NotPlaceableAttributeClass;
}

FClassReflection* FReflectionRegistry::GetDefaultToInstancedAttributeClass() const
{
	return DefaultToInstancedAttributeClass;
}

FClassReflection* FReflectionRegistry::GetConstAttributeClass() const
{
	return ConstAttributeClass;
}

FClassReflection* FReflectionRegistry::GetDeprecatedAttributeClass() const
{
	return DeprecatedAttributeClass;
}

FClassReflection* FReflectionRegistry::GetPerObjectConfigAttributeClass() const
{
	return PerObjectConfigAttributeClass;
}

FClassReflection* FReflectionRegistry::GetConfigDoNotCheckDefaultsAttributeClass() const
{
	return ConfigDoNotCheckDefaultsAttributeClass;
}

FClassReflection* FReflectionRegistry::GetDefaultConfigAttributeClass() const
{
	return DefaultConfigAttributeClass;
}

FClassReflection* FReflectionRegistry::GetEditInlineNewAttributeClass() const
{
	return EditInlineNewAttributeClass;
}

FClassReflection* FReflectionRegistry::GetNotEditInlineNewAttributeClass() const
{
	return NotEditInlineNewAttributeClass;
}

FClassReflection* FReflectionRegistry::GetHideDropdownAttributeClass() const
{
	return HideDropdownAttributeClass;
}

FClassReflection* FReflectionRegistry::GetShowCategoriesAttributeClass() const
{
	return ShowCategoriesAttributeClass;
}

FClassReflection* FReflectionRegistry::GetComponentWrapperClassAttributeClass() const
{
	return ComponentWrapperClassAttributeClass;
}

FClassReflection* FReflectionRegistry::GetHideFunctionsAttributeClass() const
{
	return HideFunctionsAttributeClass;
}

FClassReflection* FReflectionRegistry::GetAutoExpandCategoriesAttributeClass() const
{
	return AutoExpandCategoriesAttributeClass;
}

FClassReflection* FReflectionRegistry::GetAutoCollapseCategoriesAttributeClass() const
{
	return AutoCollapseCategoriesAttributeClass;
}

FClassReflection* FReflectionRegistry::GetCollapseCategoriesAttributeClass() const
{
	return CollapseCategoriesAttributeClass;
}

FClassReflection* FReflectionRegistry::GetDontCollapseCategoriesAttributeClass() const
{
	return DontCollapseCategoriesAttributeClass;
}

FClassReflection* FReflectionRegistry::GetPrioritizeCategoriesAttributeClass() const
{
	return PrioritizeCategoriesAttributeClass;
}

FClassReflection* FReflectionRegistry::GetAdvancedClassDisplayAttributeClass() const
{
	return AdvancedClassDisplayAttributeClass;
}

FClassReflection* FReflectionRegistry::GetEarlyAccessPreviewAttributeClass() const
{
	return EarlyAccessPreviewAttributeClass;
}

FClassReflection* FReflectionRegistry::GetSparseClassDataTypeAttributeClass() const
{
	return SparseClassDataTypeAttributeClass;
}

FClassReflection* FReflectionRegistry::GetGlobalConfigAttributeClass() const
{
	return GlobalConfigAttributeClass;
}

FClassReflection* FReflectionRegistry::GetLocalizedAttributeClass() const
{
	return LocalizedAttributeClass;
}

FClassReflection* FReflectionRegistry::GetDuplicateTransientAttributeClass() const
{
	return DuplicateTransientAttributeClass;
}

FClassReflection* FReflectionRegistry::GetNonPIETransientAttributeClass() const
{
	return NonPIETransientAttributeClass;
}

FClassReflection* FReflectionRegistry::GetNonPIEDuplicateTransientAttributeClass() const
{
	return NonPIEDuplicateTransientAttributeClass;
}

FClassReflection* FReflectionRegistry::GetExportAttributeClass() const
{
	return ExportAttributeClass;
}

FClassReflection* FReflectionRegistry::GetNoClearAttributeClass() const
{
	return NoClearAttributeClass;
}

FClassReflection* FReflectionRegistry::GetEditFixedSizeAttributeClass() const
{
	return EditFixedSizeAttributeClass;
}

FClassReflection* FReflectionRegistry::GetReplicatedAttributeClass() const
{
	return ReplicatedAttributeClass;
}

FClassReflection* FReflectionRegistry::GetReplicatedUsingAttributeClass() const
{
	return ReplicatedUsingAttributeClass;
}

FClassReflection* FReflectionRegistry::GetNotReplicatedAttributeClass() const
{
	return NotReplicatedAttributeClass;
}

FClassReflection* FReflectionRegistry::GetInterpAttributeClass() const
{
	return InterpAttributeClass;
}

FClassReflection* FReflectionRegistry::GetNonTransactionalAttributeClass() const
{
	return NonTransactionalAttributeClass;
}

FClassReflection* FReflectionRegistry::GetInstancedAttributeClass() const
{
	return InstancedAttributeClass;
}

FClassReflection* FReflectionRegistry::GetBlueprintAssignableAttributeClass() const
{
	return BlueprintAssignableAttributeClass;
}

FClassReflection* FReflectionRegistry::GetSimpleDisplayAttributeClass() const
{
	return SimpleDisplayAttributeClass;
}

FClassReflection* FReflectionRegistry::GetAdvancedDisplayAttributeClass() const
{
	return AdvancedDisplayAttributeClass;
}

FClassReflection* FReflectionRegistry::GetEditAnywhereAttributeClass() const
{
	return EditAnywhereAttributeClass;
}

FClassReflection* FReflectionRegistry::GetEditInstanceOnlyAttributeClass() const
{
	return EditInstanceOnlyAttributeClass;
}

FClassReflection* FReflectionRegistry::GetEditDefaultsOnlyAttributeClass() const
{
	return EditDefaultsOnlyAttributeClass;
}

FClassReflection* FReflectionRegistry::GetVisibleAnywhereAttributeClass() const
{
	return VisibleAnywhereAttributeClass;
}

FClassReflection* FReflectionRegistry::GetVisibleDefaultsOnlyAttributeClass() const
{
	return VisibleDefaultsOnlyAttributeClass;
}

FClassReflection* FReflectionRegistry::GetBlueprintReadOnlyAttributeClass() const
{
	return BlueprintReadOnlyAttributeClass;
}

FClassReflection* FReflectionRegistry::GetBlueprintReadWriteAttributeClass() const
{
	return BlueprintReadWriteAttributeClass;
}

FClassReflection* FReflectionRegistry::GetAssetRegistrySearchableAttributeClass() const
{
	return AssetRegistrySearchableAttributeClass;
}

FClassReflection* FReflectionRegistry::GetSaveGameAttributeClass() const
{
	return SaveGameAttributeClass;
}

FClassReflection* FReflectionRegistry::GetTextExportTransientAttributeClass() const
{
	return TextExportTransientAttributeClass;
}

FClassReflection* FReflectionRegistry::GetSkipSerializationAttributeClass() const
{
	return SkipSerializationAttributeClass;
}

FClassReflection* FReflectionRegistry::GetDefaultSubObjectAttributeClass() const
{
	return DefaultSubObjectAttributeClass;
}

FClassReflection* FReflectionRegistry::GetRootComponentAttributeClass() const
{
	return RootComponentAttributeClass;
}

FClassReflection* FReflectionRegistry::GetAttachmentParentAttributeClass() const
{
	return AttachmentParentAttributeClass;
}

FClassReflection* FReflectionRegistry::GetAttachmentSocketNameAttributeClass() const
{
	return AttachmentSocketNameAttributeClass;
}

FClassReflection* FReflectionRegistry::GetDefaultValueAttributeClass() const
{
	return DefaultValueAttributeClass;
}

FClassReflection* FReflectionRegistry::GetBlueprintImplementableEventAttributeClass() const
{
	return BlueprintImplementableEventAttributeClass;
}

FClassReflection* FReflectionRegistry::GetBlueprintNativeEventAttributeClass() const
{
	return BlueprintNativeEventAttributeClass;
}

FClassReflection* FReflectionRegistry::GetSealedEventAttributeClass() const
{
	return SealedEventAttributeClass;
}

FClassReflection* FReflectionRegistry::GetExecAttributeClass() const
{
	return ExecAttributeClass;
}

FClassReflection* FReflectionRegistry::GetServerAttributeClass() const
{
	return ServerAttributeClass;
}

FClassReflection* FReflectionRegistry::GetClientAttributeClass() const
{
	return ClientAttributeClass;
}

FClassReflection* FReflectionRegistry::GetNetMulticastAttributeClass() const
{
	return NetMulticastAttributeClass;
}

FClassReflection* FReflectionRegistry::GetReliableAttributeClass() const
{
	return ReliableAttributeClass;
}

FClassReflection* FReflectionRegistry::GetUnreliableAttributeClass() const
{
	return UnreliableAttributeClass;
}

FClassReflection* FReflectionRegistry::GetBlueprintPureAttributeClass() const
{
	return BlueprintPureAttributeClass;
}

FClassReflection* FReflectionRegistry::GetBlueprintCosmeticAttributeClass() const
{
	return BlueprintCosmeticAttributeClass;
}

FClassReflection* FReflectionRegistry::GetCustomThunkAttributeClass() const
{
	return CustomThunkAttributeClass;
}

FClassReflection* FReflectionRegistry::GetWithValidationAttributeClass() const
{
	return WithValidationAttributeClass;
}

FClassReflection* FReflectionRegistry::GetServiceRequestAttributeClass() const
{
	return ServiceRequestAttributeClass;
}

FClassReflection* FReflectionRegistry::GetServiceResponseAttributeClass() const
{
	return ServiceResponseAttributeClass;
}

#if WITH_EDITOR
FClassReflection* FReflectionRegistry::GetHideCategoriesAttributeClass() const
{
	return HideCategoriesAttributeClass;
}

FClassReflection* FReflectionRegistry::GetConversionRootAttributeClass() const
{
	return ConversionRootAttributeClass;
}

FClassReflection* FReflectionRegistry::GetCannotImplementInterfaceInBlueprintAttributeClass() const
{
	return CannotImplementInterfaceInBlueprintAttributeClass;
}

FClassReflection* FReflectionRegistry::GetToolTipAttributeClass() const
{
	return ToolTipAttributeClass;
}

FClassReflection* FReflectionRegistry::GetShortTooltipAttributeClass() const
{
	return ShortTooltipAttributeClass;
}

FClassReflection* FReflectionRegistry::GetDocumentationPolicyAttributeClass() const
{
	return DocumentationPolicyAttributeClass;
}

FClassReflection* FReflectionRegistry::GetBlueprintSpawnableComponentAttributeClass() const
{
	return BlueprintSpawnableComponentAttributeClass;
}

FClassReflection* FReflectionRegistry::GetChildCanTickAttributeClass() const
{
	return ChildCanTickAttributeClass;
}

FClassReflection* FReflectionRegistry::GetChildCannotTickAttributeClass() const
{
	return ChildCannotTickAttributeClass;
}

FClassReflection* FReflectionRegistry::GetDebugTreeLeafAttributeClass() const
{
	return DebugTreeLeafAttributeClass;
}

FClassReflection* FReflectionRegistry::GetIgnoreCategoryKeywordsInSubclassesAttributeClass() const
{
	return IgnoreCategoryKeywordsInSubclassesAttributeClass;
}

FClassReflection* FReflectionRegistry::GetDeprecatedNodeAttributeClass() const
{
	return DeprecatedNodeAttributeClass;
}

FClassReflection* FReflectionRegistry::GetDeprecationMessageAttributeClass() const
{
	return DeprecationMessageAttributeClass;
}

FClassReflection* FReflectionRegistry::GetDisplayNameAttributeClass() const
{
	return DisplayNameAttributeClass;
}

FClassReflection* FReflectionRegistry::GetScriptNameAttributeClass() const
{
	return ScriptNameAttributeClass;
}

FClassReflection* FReflectionRegistry::GetIsBlueprintBaseAttributeClass() const
{
	return IsBlueprintBaseAttributeClass;
}

FClassReflection* FReflectionRegistry::GetKismetHideOverridesAttributeClass() const
{
	return KismetHideOverridesAttributeClass;
}

FClassReflection* FReflectionRegistry::GetLoadBehaviorAttributeClass() const
{
	return LoadBehaviorAttributeClass;
}

FClassReflection* FReflectionRegistry::GetProhibitedInterfacesAttributeClass() const
{
	return ProhibitedInterfacesAttributeClass;
}

FClassReflection* FReflectionRegistry::GetRestrictedToClassesAttributeClass() const
{
	return RestrictedToClassesAttributeClass;
}

FClassReflection* FReflectionRegistry::GetShowWorldContextPinAttributeClass() const
{
	return ShowWorldContextPinAttributeClass;
}

FClassReflection* FReflectionRegistry::GetDontUseGenericSpawnObjectAttributeClass() const
{
	return DontUseGenericSpawnObjectAttributeClass;
}

FClassReflection* FReflectionRegistry::GetExposedAsyncProxyAttributeClass() const
{
	return ExposedAsyncProxyAttributeClass;
}

FClassReflection* FReflectionRegistry::GetBlueprintThreadSafeAttributeClass() const
{
	return BlueprintThreadSafeAttributeClass;
}

FClassReflection* FReflectionRegistry::GetUsesHierarchyAttributeClass() const
{
	return UsesHierarchyAttributeClass;
}

FClassReflection* FReflectionRegistry::GetHasNativeBreakAttributeClass() const
{
	return HasNativeBreakAttributeClass;
}

FClassReflection* FReflectionRegistry::GetHasNativeMakeAttributeClass() const
{
	return HasNativeMakeAttributeClass;
}

FClassReflection* FReflectionRegistry::GetHiddenByDefaultAttributeClass() const
{
	return HiddenByDefaultAttributeClass;
}

FClassReflection* FReflectionRegistry::GetDisableSplitPinAttributeClass() const
{
	return DisableSplitPinAttributeClass;
}

FClassReflection* FReflectionRegistry::GetAllowAbstractAttributeClass() const
{
	return AllowAbstractAttributeClass;
}

FClassReflection* FReflectionRegistry::GetAllowAnyActorAttributeClass() const
{
	return AllowAnyActorAttributeClass;
}

FClassReflection* FReflectionRegistry::GetAllowedClassesAttributeClass() const
{
	return AllowedClassesAttributeClass;
}

FClassReflection* FReflectionRegistry::GetAllowPreserveRatioAttributeClass() const
{
	return AllowPreserveRatioAttributeClass;
}

FClassReflection* FReflectionRegistry::GetAllowPrivateAccessAttributeClass() const
{
	return AllowPrivateAccessAttributeClass;
}

FClassReflection* FReflectionRegistry::GetArrayClampAttributeClass() const
{
	return ArrayClampAttributeClass;
}

FClassReflection* FReflectionRegistry::GetAssetBundlesAttributeClass() const
{
	return AssetBundlesAttributeClass;
}

FClassReflection* FReflectionRegistry::GetBlueprintBaseOnlyAttributeClass() const
{
	return BlueprintBaseOnlyAttributeClass;
}

FClassReflection* FReflectionRegistry::GetBlueprintCompilerGeneratedDefaultsAttributeClass() const
{
	return BlueprintCompilerGeneratedDefaultsAttributeClass;
}

FClassReflection* FReflectionRegistry::GetClampMinAttributeClass() const
{
	return ClampMinAttributeClass;
}

FClassReflection* FReflectionRegistry::GetClampMaxAttributeClass() const
{
	return ClampMaxAttributeClass;
}

FClassReflection* FReflectionRegistry::GetConfigHierarchyEditableAttributeClass() const
{
	return ConfigHierarchyEditableAttributeClass;
}

FClassReflection* FReflectionRegistry::GetContentDirAttributeClass() const
{
	return ContentDirAttributeClass;
}

FClassReflection* FReflectionRegistry::GetDeltaAttributeClass() const
{
	return DeltaAttributeClass;
}

FClassReflection* FReflectionRegistry::GetDeprecatedPropertyAttributeClass() const
{
	return DeprecatedPropertyAttributeClass;
}

FClassReflection* FReflectionRegistry::GetDisallowedAssetDataTagsAttributeClass() const
{
	return DisallowedAssetDataTagsAttributeClass;
}

FClassReflection* FReflectionRegistry::GetDisallowedClassesAttributeClass() const
{
	return DisallowedClassesAttributeClass;
}

FClassReflection* FReflectionRegistry::GetDisplayAfterAttributeClass() const
{
	return DisplayAfterAttributeClass;
}

FClassReflection* FReflectionRegistry::GetDisplayPriorityAttributeClass() const
{
	return DisplayPriorityAttributeClass;
}

FClassReflection* FReflectionRegistry::GetDisplayThumbnailAttributeClass() const
{
	return DisplayThumbnailAttributeClass;
}

FClassReflection* FReflectionRegistry::GetEditConditionAttributeClass() const
{
	return EditConditionAttributeClass;
}

FClassReflection* FReflectionRegistry::GetEditConditionHidesAttributeClass() const
{
	return EditConditionHidesAttributeClass;
}

FClassReflection* FReflectionRegistry::GetEditFixedOrderAttributeClass() const
{
	return EditFixedOrderAttributeClass;
}

FClassReflection* FReflectionRegistry::GetCategoryAttributeClass() const
{
	return CategoryAttributeClass;
}

FClassReflection* FReflectionRegistry::GetExactClassAttributeClass() const
{
	return ExactClassAttributeClass;
}

FClassReflection* FReflectionRegistry::GetExposeFunctionCategoriesAttributeClass() const
{
	return ExposeFunctionCategoriesAttributeClass;
}

FClassReflection* FReflectionRegistry::GetExposeOnSpawnAttributeClass() const
{
	return ExposeOnSpawnAttributeClass;
}

FClassReflection* FReflectionRegistry::GetFilePathFilterAttributeClass() const
{
	return FilePathFilterAttributeClass;
}

FClassReflection* FReflectionRegistry::GetRelativeToGameDirAttributeClass() const
{
	return RelativeToGameDirAttributeClass;
}

FClassReflection* FReflectionRegistry::GetFixedIncrementAttributeClass() const
{
	return FixedIncrementAttributeClass;
}

FClassReflection* FReflectionRegistry::GetForceShowEngineContentAttributeClass() const
{
	return ForceShowEngineContentAttributeClass;
}

FClassReflection* FReflectionRegistry::GetForceShowPluginContentAttributeClass() const
{
	return ForceShowPluginContentAttributeClass;
}

FClassReflection* FReflectionRegistry::GetHideAlphaChannelAttributeClass() const
{
	return HideAlphaChannelAttributeClass;
}

FClassReflection* FReflectionRegistry::GetHideInDetailPanelAttributeClass() const
{
	return HideInDetailPanelAttributeClass;
}

FClassReflection* FReflectionRegistry::GetHideViewOptionsAttributeClass() const
{
	return HideViewOptionsAttributeClass;
}

FClassReflection* FReflectionRegistry::GetIgnoreForMemberInitializationTestAttributeClass() const
{
	return IgnoreForMemberInitializationTestAttributeClass;
}

FClassReflection* FReflectionRegistry::GetInlineEditConditionToggleAttributeClass() const
{
	return InlineEditConditionToggleAttributeClass;
}

FClassReflection* FReflectionRegistry::GetLinearDeltaSensitivityAttributeClass() const
{
	return LinearDeltaSensitivityAttributeClass;
}

FClassReflection* FReflectionRegistry::GetLongPackageNameAttributeClass() const
{
	return LongPackageNameAttributeClass;
}

FClassReflection* FReflectionRegistry::GetMakeEditWidgetAttributeClass() const
{
	return MakeEditWidgetAttributeClass;
}

FClassReflection* FReflectionRegistry::GetMakeStructureDefaultValueAttributeClass() const
{
	return MakeStructureDefaultValueAttributeClass;
}

FClassReflection* FReflectionRegistry::GetMetaClassAttributeClass() const
{
	return MetaClassAttributeClass;
}

FClassReflection* FReflectionRegistry::GetMustImplementAttributeClass() const
{
	return MustImplementAttributeClass;
}

FClassReflection* FReflectionRegistry::GetMultipleAttributeClass() const
{
	return MultipleAttributeClass;
}

FClassReflection* FReflectionRegistry::GetMaxLengthAttributeClass() const
{
	return MaxLengthAttributeClass;
}

FClassReflection* FReflectionRegistry::GetMultiLineAttributeClass() const
{
	return MultiLineAttributeClass;
}

FClassReflection* FReflectionRegistry::GetPasswordFieldAttributeClass() const
{
	return PasswordFieldAttributeClass;
}

FClassReflection* FReflectionRegistry::GetNoElementDuplicateAttributeClass() const
{
	return NoElementDuplicateAttributeClass;
}

FClassReflection* FReflectionRegistry::GetNoResetToDefaultAttributeClass() const
{
	return NoResetToDefaultAttributeClass;
}

FClassReflection* FReflectionRegistry::GetEditInlineAttributeClass() const
{
	return EditInlineAttributeClass;
}

FClassReflection* FReflectionRegistry::GetNoEditInlineAttributeClass() const
{
	return NoEditInlineAttributeClass;
}

FClassReflection* FReflectionRegistry::GetNoSpinboxAttributeClass() const
{
	return NoSpinboxAttributeClass;
}

FClassReflection* FReflectionRegistry::GetOnlyPlaceableAttributeClass() const
{
	return OnlyPlaceableAttributeClass;
}

FClassReflection* FReflectionRegistry::GetRelativePathAttributeClass() const
{
	return RelativePathAttributeClass;
}

FClassReflection* FReflectionRegistry::GetRelativeToGameContentDirAttributeClass() const
{
	return RelativeToGameContentDirAttributeClass;
}

FClassReflection* FReflectionRegistry::GetRequiredAssetDataTagsAttributeClass() const
{
	return RequiredAssetDataTagsAttributeClass;
}

FClassReflection* FReflectionRegistry::GetScriptNoExportAttributeClass() const
{
	return ScriptNoExportAttributeClass;
}

FClassReflection* FReflectionRegistry::GetShowOnlyInnerPropertiesAttributeClass() const
{
	return ShowOnlyInnerPropertiesAttributeClass;
}

FClassReflection* FReflectionRegistry::GetShowTreeViewAttributeClass() const
{
	return ShowTreeViewAttributeClass;
}

FClassReflection* FReflectionRegistry::GetSliderExponentAttributeClass() const
{
	return SliderExponentAttributeClass;
}

FClassReflection* FReflectionRegistry::GetTitlePropertyAttributeClass() const
{
	return TitlePropertyAttributeClass;
}

FClassReflection* FReflectionRegistry::GetUIMinAttributeClass() const
{
	return UIMinAttributeClass;
}

FClassReflection* FReflectionRegistry::GetUIMaxAttributeClass() const
{
	return UIMaxAttributeClass;
}

FClassReflection* FReflectionRegistry::GetUnitsAttributeClass() const
{
	return UnitsAttributeClass;
}

FClassReflection* FReflectionRegistry::GetForceUnitsAttributeClass() const
{
	return ForceUnitsAttributeClass;
}

FClassReflection* FReflectionRegistry::GetUntrackedAttributeClass() const
{
	return UntrackedAttributeClass;
}

FClassReflection* FReflectionRegistry::GetDevelopmentOnlyAttributeClass() const
{
	return DevelopmentOnlyAttributeClass;
}

FClassReflection* FReflectionRegistry::GetNeedsLatentFixupAttributeClass() const
{
	return NeedsLatentFixupAttributeClass;
}

FClassReflection* FReflectionRegistry::GetLatentCallbackTargetAttributeClass() const
{
	return LatentCallbackTargetAttributeClass;
}

FClassReflection* FReflectionRegistry::GetGetOptionsAttributeClass() const
{
	return GetOptionsAttributeClass;
}

FClassReflection* FReflectionRegistry::GetPinHiddenByDefaultAttributeClass() const
{
	return PinHiddenByDefaultAttributeClass;
}

FClassReflection* FReflectionRegistry::GetValidEnumValuesAttributeClass() const
{
	return ValidEnumValuesAttributeClass;
}

FClassReflection* FReflectionRegistry::GetInvalidEnumValuesAttributeClass() const
{
	return InvalidEnumValuesAttributeClass;
}

FClassReflection* FReflectionRegistry::GetOverridingInputPropertyAttributeClass() const
{
	return OverridingInputPropertyAttributeClass;
}

FClassReflection* FReflectionRegistry::GetRequiredInputAttributeClass() const
{
	return RequiredInputAttributeClass;
}

FClassReflection* FReflectionRegistry::GetNeverAsPinAttributeClass() const
{
	return NeverAsPinAttributeClass;
}

FClassReflection* FReflectionRegistry::GetPinShownByDefaultAttributeClass() const
{
	return PinShownByDefaultAttributeClass;
}

FClassReflection* FReflectionRegistry::GetAlwaysAsPinAttributeClass() const
{
	return AlwaysAsPinAttributeClass;
}

FClassReflection* FReflectionRegistry::GetCustomizePropertyAttributeClass() const
{
	return CustomizePropertyAttributeClass;
}

FClassReflection* FReflectionRegistry::GetCallInEditorAttributeClass() const
{
	return CallInEditorAttributeClass;
}

FClassReflection* FReflectionRegistry::GetVariadicAttributeClass() const
{
	return VariadicAttributeClass;
}

FClassReflection* FReflectionRegistry::GetReturnDisplayNameAttributeClass() const
{
	return ReturnDisplayNameAttributeClass;
}

FClassReflection* FReflectionRegistry::GetInternalUseParamAttributeClass() const
{
	return InternalUseParamAttributeClass;
}

FClassReflection* FReflectionRegistry::GetForceAsFunctionAttributeClass() const
{
	return ForceAsFunctionAttributeClass;
}

FClassReflection* FReflectionRegistry::GetIgnoreTypePromotionAttributeClass() const
{
	return IgnoreTypePromotionAttributeClass;
}

FClassReflection* FReflectionRegistry::GetArrayParmAttributeClass() const
{
	return ArrayParmAttributeClass;
}

FClassReflection* FReflectionRegistry::GetArrayTypeDependentParamsAttributeClass() const
{
	return ArrayTypeDependentParamsAttributeClass;
}

FClassReflection* FReflectionRegistry::GetAutoCreateRefTermAttributeClass() const
{
	return AutoCreateRefTermAttributeClass;
}

FClassReflection* FReflectionRegistry::GetHideAssetPickerAttributeClass() const
{
	return HideAssetPickerAttributeClass;
}

FClassReflection* FReflectionRegistry::GetBlueprintInternalUseOnlyAttributeClass() const
{
	return BlueprintInternalUseOnlyAttributeClass;
}

FClassReflection* FReflectionRegistry::GetBlueprintProtectedAttributeClass() const
{
	return BlueprintProtectedAttributeClass;
}

FClassReflection* FReflectionRegistry::GetCallableWithoutWorldContextAttributeClass() const
{
	return CallableWithoutWorldContextAttributeClass;
}

FClassReflection* FReflectionRegistry::GetCommutativeAssociativeBinaryOperatorAttributeClass() const
{
	return CommutativeAssociativeBinaryOperatorAttributeClass;
}

FClassReflection* FReflectionRegistry::GetCompactNodeTitleAttributeClass() const
{
	return CompactNodeTitleAttributeClass;
}

FClassReflection* FReflectionRegistry::GetCustomStructureParamAttributeClass() const
{
	return CustomStructureParamAttributeClass;
}

FClassReflection* FReflectionRegistry::GetDefaultToSelfAttributeClass() const
{
	return DefaultToSelfAttributeClass;
}

FClassReflection* FReflectionRegistry::GetDeprecatedFunctionAttributeClass() const
{
	return DeprecatedFunctionAttributeClass;
}

FClassReflection* FReflectionRegistry::GetExpandEnumAsExecsAttributeClass() const
{
	return ExpandEnumAsExecsAttributeClass;
}

FClassReflection* FReflectionRegistry::GetExpandBoolAsExecsAttributeClass() const
{
	return ExpandBoolAsExecsAttributeClass;
}

FClassReflection* FReflectionRegistry::GetScriptMethodAttributeClass() const
{
	return ScriptMethodAttributeClass;
}

FClassReflection* FReflectionRegistry::GetScriptMethodSelfReturnAttributeClass() const
{
	return ScriptMethodSelfReturnAttributeClass;
}

FClassReflection* FReflectionRegistry::GetScriptOperatorAttributeClass() const
{
	return ScriptOperatorAttributeClass;
}

FClassReflection* FReflectionRegistry::GetScriptConstantAttributeClass() const
{
	return ScriptConstantAttributeClass;
}

FClassReflection* FReflectionRegistry::GetScriptConstantHostAttributeClass() const
{
	return ScriptConstantHostAttributeClass;
}

FClassReflection* FReflectionRegistry::GetHidePinAttributeClass() const
{
	return HidePinAttributeClass;
}

FClassReflection* FReflectionRegistry::GetHideSpawnParmsAttributeClass() const
{
	return HideSpawnParmsAttributeClass;
}

FClassReflection* FReflectionRegistry::GetKeywordsAttributeClass() const
{
	return KeywordsAttributeClass;
}

FClassReflection* FReflectionRegistry::GetLatentAttributeClass() const
{
	return LatentAttributeClass;
}

FClassReflection* FReflectionRegistry::GetLatentInfoAttributeClass() const
{
	return LatentInfoAttributeClass;
}

FClassReflection* FReflectionRegistry::GetMaterialParameterCollectionFunctionAttributeClass() const
{
	return MaterialParameterCollectionFunctionAttributeClass;
}

FClassReflection* FReflectionRegistry::GetNativeBreakFuncAttributeClass() const
{
	return NativeBreakFuncAttributeClass;
}

FClassReflection* FReflectionRegistry::GetNativeMakeFuncAttributeClass() const
{
	return NativeMakeFuncAttributeClass;
}

FClassReflection* FReflectionRegistry::GetUnsafeDuringActorConstructionAttributeClass() const
{
	return UnsafeDuringActorConstructionAttributeClass;
}

FClassReflection* FReflectionRegistry::GetWorldContextAttributeClass() const
{
	return WorldContextAttributeClass;
}

FClassReflection* FReflectionRegistry::GetBlueprintAutoCastAttributeClass() const
{
	return BlueprintAutoCastAttributeClass;
}

FClassReflection* FReflectionRegistry::GetNotBlueprintThreadSafeAttributeClass() const
{
	return NotBlueprintThreadSafeAttributeClass;
}

FClassReflection* FReflectionRegistry::GetDeterminesOutputTypeAttributeClass() const
{
	return DeterminesOutputTypeAttributeClass;
}

FClassReflection* FReflectionRegistry::GetDynamicOutputParamAttributeClass() const
{
	return DynamicOutputParamAttributeClass;
}

FClassReflection* FReflectionRegistry::GetDataTablePinAttributeClass() const
{
	return DataTablePinAttributeClass;
}

FClassReflection* FReflectionRegistry::GetSetParamAttributeClass() const
{
	return SetParamAttributeClass;
}

FClassReflection* FReflectionRegistry::GetMapParamAttributeClass() const
{
	return MapParamAttributeClass;
}

FClassReflection* FReflectionRegistry::GetMapKeyParamAttributeClass() const
{
	return MapKeyParamAttributeClass;
}

FClassReflection* FReflectionRegistry::GetMapValueParamAttributeClass() const
{
	return MapValueParamAttributeClass;
}

FClassReflection* FReflectionRegistry::GetBitmaskAttributeClass() const
{
	return BitmaskAttributeClass;
}

FClassReflection* FReflectionRegistry::GetBitmaskEnumAttributeClass() const
{
	return BitmaskEnumAttributeClass;
}

FClassReflection* FReflectionRegistry::GetBitflagsAttributeClass() const
{
	return BitflagsAttributeClass;
}

FClassReflection* FReflectionRegistry::GetUseEnumValuesAsMaskValuesInEditorAttributeClass() const
{
	return UseEnumValuesAsMaskValuesInEditorAttributeClass;
}

FClassReflection* FReflectionRegistry::GetArrayParamAttributeClass() const
{
	return ArrayParamAttributeClass;
}
#endif

MonoClass* FReflectionRegistry::GetMonoClass(const TWeakObjectPtr<UField>& InField)
{
	if (const auto Class = Cast<UClass>(InField))
	{
		if (Class->HasAnyClassFlags(CLASS_Interface))
		{
			return FMonoDomain::Class_From_Name(
				FUnrealCSharpFunctionLibrary::GetClassNameSpace(Class),
				FUnrealCSharpFunctionLibrary::GetFullInterface(Class));
		}

		return FMonoDomain::Class_From_Name(
			FUnrealCSharpFunctionLibrary::GetClassNameSpace(Class),
			FUnrealCSharpFunctionLibrary::GetFullClass(Class));
	}

	if (const auto ScriptStruct = Cast<UScriptStruct>(InField))
	{
		return FMonoDomain::Class_From_Name(
			FUnrealCSharpFunctionLibrary::GetClassNameSpace(ScriptStruct),
			FUnrealCSharpFunctionLibrary::GetFullClass(ScriptStruct));
	}

	if (const auto Enum = Cast<UEnum>(InField))
	{
		return FMonoDomain::Class_From_Name(
			FUnrealCSharpFunctionLibrary::GetClassNameSpace(Enum),
			FUnrealCSharpFunctionLibrary::GetFullClass(Enum));
	}

	return nullptr;
}
