#pragma once

#include "CoreMinimal.h"

struct FProjectContextInfo;
struct FDynamicClassViewerNode;
struct FNewClassInfo;
class IClassViewerFilter;
class SEditableTextBox;
class SWizard;
class SDynamicClassViewer;
struct FNewClassInfo;

class SDynamicNewClassDialog : public SCompoundWidget
{
public:
	SLATE_BEGIN_ARGS(SDynamicNewClassDialog)
		{
		}

		SLATE_ARGUMENT(TSharedPtr<SWindow>, ParentWindow)

		SLATE_ARGUMENT(FString, InitialPath)

	SLATE_END_ARGS()

	void Construct(const FArguments& InArgs);

	virtual FReply OnKeyDown(const FGeometry& MyGeometry, const FKeyEvent& InKeyEvent) override;

	virtual void Tick(const FGeometry& AllottedGeometry, const double InCurrentTime, const float InDeltaTime) override;

private:
	TSharedRef<ITableRow> MakeParentClassListViewWidget(TSharedPtr<FNewClassInfo> ParentClassItem,
	                                                    const TSharedRef<STableViewBase>& OwnerTable);

	FText GetSelectedParentClassName() const;

	void OnCommonClassItemSelected(TSharedPtr<FNewClassInfo> Item, ESelectInfo::Type SelectInfo);

	void OnCommonClassItemDoubleClicked(TSharedPtr<FNewClassInfo> Item);

	void OnAllClassItemSelected(TSharedPtr<FDynamicClassViewerNode> Item);

	void OnAllClassItemDoubleClicked(TSharedPtr<FDynamicClassViewerNode> Item);

	void MainWizardShowNextPage() const;

	bool IsAllClassShown() const;

	void OnAllClassVisibilityChanged(bool bInShowFullClassTree);

	EVisibility GetCommonClassVisibility() const;

	EVisibility GetAllClassVisibility() const;

	EVisibility GetNameErrorLabelVisibility() const;

	void OnNewClassTypeChanged(const int32 NewTypeIndex);

	FText GetNameErrorLabelText() const;

	void OnNamePageEntered();

	FText GetNameClassTitle() const;

	FText OnGetClassNameText() const;

	void OnClassNameTextChanged(const FText& NewText);

	void OnClassNameTextCommitted(const FText& NewText, ETextCommit::Type CommitType);

	FText OnGetClassPathText() const;

	void OnClassPathTextChanged(const FText& NewText);

	FText OnGetParentClassNameText() const;

	FText OnGetDynamicFilePathText() const;

	FString GetDynamicFileName() const;

	void CancelClicked();

	bool CanFinish() const;

	void FinishClicked();

	FReply HandleChooseFolderButtonClicked();

	FText GetSelectedProjectComboText() const;

	void SelectedProjectComboBoxSelectionChanged(TSharedPtr<FProjectContextInfo> Value, ESelectInfo::Type SelectInfo);

	TSharedRef<SWidget> MakeWidgetForSelectedModuleCombo(TSharedPtr<FProjectContextInfo> Value);

private:
	void UpdateInputValidity();

	void SetupDefaultCommonParentClassItems();

	void CloseContainingWindow();

private:
	TSharedPtr<SWizard> MainWizard;

	TSharedPtr<SListView<TSharedPtr<FNewClassInfo>>> ParentClassListView;

	TArray<TSharedPtr<FNewClassInfo>> ParentClassItemsSource;

	TSharedPtr<SDynamicClassViewer> DynamicClassViewer;

	FDelegateHandle DynamicClassUpdatedDelegateHandle;

	int32 NewClassTypeIndex;

	TSharedPtr<SEditableTextBox> ClassNameEditBox;

	TSharedPtr<SComboBox<TSharedPtr<FProjectContextInfo>>> AvailableProjectsCombo;

	static FString LastSelectedModuleName;

	FString NewClassName;

	FString NewClassPath;

	FString CalculatedClassHeaderName;

	FString CalculatedClassSourceName;

	FString LastAutoGeneratedClassName;

	TSharedPtr<FDynamicClassViewerNode> SelectedParentClassInfo;

	bool bShowFullClassTree;

	double LastPeriodicValidityCheckTime;

	double PeriodicValidityCheckFrequency;

	bool bPreventPeriodicValidityChecksUntilNextChange;

	FText LastInputValidityErrorText;

	bool bLastInputValidityCheckSuccessful;

	TArray<TSharedPtr<FProjectContextInfo>> AvailableProjects;

	TSharedPtr<FProjectContextInfo> SelectedProjectInfo;
};
