#pragma once

#include "CoreMacro/BufferMacro.h"
#include "Domain/Script/IManagedHandle.h"

#define BINDING_CONSTRUCTOR_SIGNATURE IManagedHandle InManagedObject, IN_BUFFER_SIGNATURE, OUT_BUFFER_SIGNATURE

#define BINDING_CONSTRUCTOR_PARAM InManagedObject, IN_BUFFER, OUT_BUFFER

#define BINDING_DESTRUCTOR_SIGNATURE const IManagedHandle InManagedHandle

#define BINDING_DESTRUCTOR_PARAM InManagedHandle

#define BINDING_FUNCTION_SIGNATURE const IManagedHandle InManagedHandle, IN_BUFFER_SIGNATURE, OUT_BUFFER_SIGNATURE, RETURN_BUFFER_SIGNATURE

#define BINDING_FUNCTION_PARAM InManagedHandle, IN_BUFFER, OUT_BUFFER, RETURN_BUFFER

#define BINDING_SUBSCRIPT_GET_SIGNATURE const IManagedHandle InManagedHandle, IN_BUFFER_SIGNATURE, RETURN_BUFFER_SIGNATURE

#define BINDING_SUBSCRIPT_GET_PARAM InManagedHandle, IN_BUFFER, RETURN_BUFFER

#define BINDING_SUBSCRIPT_SET_SIGNATURE const IManagedHandle InManagedHandle, IN_BUFFER_SIGNATURE

#define BINDING_SUBSCRIPT_SET_PARAM InManagedHandle, IN_BUFFER

#define BINDING_PROPERTY_BUILDER_GET_SIGNATURE const IManagedHandle InManagedHandle, RETURN_BUFFER_SIGNATURE

#define BINDING_PROPERTY_BUILDER_GET_PARAM InManagedHandle, RETURN_BUFFER
