#pragma once

#include "GarbageCollection/FGarbageCollectionHandle.h"
#include "Macro/PropertyMacro.h"
#include "mono/metadata/object.h"

class FPropertyImplementation
{
public:
	OBJECT_PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(Byte, uint8)

	OBJECT_PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(UInt16, uint16)

	OBJECT_PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(UInt32, uint32)

	OBJECT_PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(UInt64, uint64)

	OBJECT_PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(SByte, int8)

	OBJECT_PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(Int16, int16)

	OBJECT_PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(Int, int32)

	OBJECT_PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(Int64, int64)

	OBJECT_PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(Bool, bool)

	OBJECT_PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(Float, float)

	OBJECT_COMPOUND_PROPERTY_IMPLEMENTATION_DEFINE(Compound)

	OBJECT_PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(Double, double)

	STRUCT_PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(Byte, uint8)

	STRUCT_PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(UInt16, uint16)

	STRUCT_PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(UInt32, uint32)

	STRUCT_PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(UInt64, uint64)

	STRUCT_PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(SByte, int8)

	STRUCT_PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(Int16, int16)

	STRUCT_PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(Int, int32)

	STRUCT_PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(Int64, int64)

	STRUCT_PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(Bool, bool)

	STRUCT_PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(Float, float)

	STRUCT_COMPOUND_PROPERTY_IMPLEMENTATION_DEFINE(Compound)

	STRUCT_PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(Double, double)
};
