#pragma once

#include "Macro/PropertyMacro.h"
#include "mono/metadata/object.h"

class FPropertyImplementation
{
public:
	PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(Byte, uint8)

	PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(UInt16, uint16)

	PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(UInt32, uint32)

	PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(Int8, int8)

	PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(Int16, int16)

	PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(Int, int32)

	PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(Int64, int64)

	PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(Bool, bool)

	PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(Float, float)

	COMPOUND_PROPERTY_IMPLEMENTATION_DEFINE(Object, MonoObject)

	COMPOUND_PROPERTY_IMPLEMENTATION_DEFINE(Array, MonoObject)

	PRIMITIVE_PROPERTY_IMPLEMENTATION_DEFINE(Double, double)

	COMPOUND_PROPERTY_IMPLEMENTATION_DEFINE(Map, MonoObject)

	COMPOUND_PROPERTY_IMPLEMENTATION_DEFINE(Set, MonoObject)
};
